"use client";

import { Download, Printer } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { CancelState } from "@/components/prescriptions/types";

interface PrescriptionActionsSidebarProps {
  generatedAt: string;
  generatedBy: string;
  isCancelled: boolean;
  cancelState: CancelState | null;
  onPrint: () => void;
  onDownload: () => void;
  actionsDisabled?: boolean;
}

export function PrescriptionActionsSidebar({
  generatedAt,
  generatedBy,
  isCancelled,
  cancelState,
  onPrint,
  onDownload,
  actionsDisabled = false,
}: PrescriptionActionsSidebarProps) {
  const shouldDisableActions = actionsDisabled || isCancelled;

  return (
    <div className="space-y-4">
      <Card className="rounded-2xl shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">Actions</CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <Button type="button" variant="outline" className="min-h-11 w-full justify-start" onClick={onPrint} disabled={shouldDisableActions}>
            <Printer className="mr-2 h-4 w-4" />
            Print Prescription
          </Button>
          <Button type="button" variant="outline" className="min-h-11 w-full justify-start" onClick={onDownload} disabled={shouldDisableActions}>
            <Download className="mr-2 h-4 w-4" />
            Download PDF
          </Button>
        </CardContent>
      </Card>

      <Card className="rounded-2xl shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-base">Prescription Status</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground">Status</span>
            <Badge className={isCancelled ? "bg-red-600 text-white hover:bg-red-600" : "bg-emerald-600 text-white hover:bg-emerald-600"}>
              {isCancelled ? "Cancelled" : "Active"}
            </Badge>
          </div>
          <div>
            <p className="text-muted-foreground">Generated At</p>
            <p className="font-medium">{generatedAt}</p>
          </div>
          <div>
            <p className="text-muted-foreground">Generated By</p>
            <p className="font-medium">{generatedBy}</p>
          </div>
          {cancelState ? (
            <>
              <div>
                <p className="text-muted-foreground">Cancelled At</p>
                <p className="font-medium">{cancelState.cancelledAt}</p>
              </div>
              <div>
                <p className="text-muted-foreground">Cancelled By</p>
                <p className="font-medium">{cancelState.cancelledBy}</p>
              </div>
              <div>
                <p className="text-muted-foreground">Cancellation Reason</p>
                <p className="font-medium">
                  {cancelState.reason}
                  {cancelState.reasonText ? ` — ${cancelState.reasonText}` : ""}
                </p>
              </div>
            </>
          ) : null}
        </CardContent>
      </Card>
    </div>
  );
}
