# Generated by Django 5.0.7 on 2026-07-13 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trace_version', models.PositiveIntegerField(default=1)),
                ('projection_version', models.PositiveIntegerField(default=1)),
                ('workflow_fingerprint', models.CharField(max_length=71)),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('workflow_instance_id', models.CharField(max_length=36, unique=True)),
                ('parent_workflow_instance_id', models.CharField(blank=True, max_length=36, null=True)),
                ('workflow_depth', models.PositiveSmallIntegerField(default=0)),
                ('workflow_type', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Routing', 'Routing'), ('ReportDelivery', 'Report Delivery'), ('Notification', 'Notification'), ('Payment', 'Payment'), ('WhatsAppFlow', 'WhatsApp Flow'), ('HomeCollection', 'Home Collection'), ('Marketplace', 'Marketplace'), ('Laboratory', 'Laboratory')], max_length=32)),
                ('resource_type', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Decision', 'Decision'), ('Communication', 'Communication'), ('Order', 'Order'), ('Assignment', 'Assignment'), ('Collection', 'Collection'), ('Report', 'Report'), ('Message', 'Message'), ('Payment', 'Payment'), ('Subscription', 'Subscription'), ('Workflow', 'Workflow')], max_length=32)),
                ('resource_id', models.CharField(max_length=64)),
                ('organization_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Running', 'Running'), ('Waiting', 'Waiting'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], max_length=16)),
                ('current_state', models.CharField(blank=True, default='', max_length=64)),
                ('workflow_step', models.CharField(blank=True, max_length=128, null=True)),
                ('last_event', models.CharField(max_length=128)),
                ('last_sequence_no', models.PositiveIntegerField(blank=True, null=True)),
                ('last_source', models.CharField(choices=[('ClinicalAudit', 'Clinical Audit'), ('BusinessAudit', 'Business Audit'), ('Manual', 'Manual'), ('System', 'System')], default='System', max_length=32)),
                ('sync_status', models.CharField(choices=[('Pending', 'Pending'), ('Indexed', 'Indexed'), ('Failed', 'Failed'), ('Retry', 'Retry')], default='Pending', max_length=16)),
                ('workflow_health', models.CharField(choices=[('Healthy', 'Healthy'), ('Warning', 'Warning'), ('Failed', 'Failed'), ('Blocked', 'Blocked')], default='Healthy', max_length=16)),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_clinical_audit_id', models.UUIDField(blank=True, null=True)),
                ('last_business_audit_id', models.UUIDField(blank=True, null=True)),
                ('search_vector', models.JSONField(blank=True, default=dict)),
                ('patient_account_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('patient_profile_id', models.CharField(blank=True, max_length=64, null=True)),
                ('consultation_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('encounter_id', models.CharField(blank=True, max_length=64, null=True)),
                ('recommendation_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('booking_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('routing_id', models.CharField(blank=True, max_length=64, null=True)),
                ('report_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('prescription_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=64, null=True)),
                ('laboratory_id', models.CharField(blank=True, max_length=64, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_trace',
                'indexes': [models.Index(fields=['workflow_fingerprint'], name='st_fingerprint_idx'), models.Index(fields=['parent_workflow_instance_id'], name='st_parent_idx'), models.Index(fields=['correlation_id', 'updated_at'], name='st_corr_upd_idx'), models.Index(fields=['workflow_instance_id', 'updated_at'], name='st_wf_upd_idx'), models.Index(fields=['resource_type', 'resource_id'], name='st_resource_idx'), models.Index(fields=['patient_account_id', 'updated_at'], name='st_pat_upd_idx'), models.Index(fields=['sync_status', 'updated_at'], name='st_sync_upd_idx'), models.Index(fields=['organization_id'], name='st_organization_idx'), models.Index(fields=['status'], name='st_status_idx'), models.Index(fields=['sync_status'], name='st_sync_status_idx'), models.Index(fields=['workflow_health'], name='st_health_idx'), models.Index(fields=['last_source'], name='st_last_source_idx')],
            },
        ),
    ]
