# Generated by Django 5.0.7 on 2026-07-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_trace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporttrace',
            name='current_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='supporttrace',
            name='parent_workflow_instance_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='supporttrace',
            name='resource_type',
            field=models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Decision', 'Decision'), ('Communication', 'Communication'), ('Order', 'Order'), ('Assignment', 'Assignment'), ('Collection', 'Collection'), ('Report', 'Report'), ('Consultation', 'Consultation'), ('Prescription', 'Prescription'), ('Message', 'Message'), ('Payment', 'Payment'), ('Subscription', 'Subscription'), ('Workflow', 'Workflow')], max_length=32),
        ),
        migrations.AlterField(
            model_name='supporttrace',
            name='workflow_instance_id',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='supporttrace',
            name='workflow_type',
            field=models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Routing', 'Routing'), ('ReportDelivery', 'Report Delivery'), ('Consultation', 'Consultation'), ('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report'), ('Notification', 'Notification'), ('Payment', 'Payment'), ('WhatsAppFlow', 'WhatsApp Flow'), ('HomeCollection', 'Home Collection'), ('Marketplace', 'Marketplace'), ('Laboratory', 'Laboratory')], max_length=32),
        ),
    ]
