# Generated by Django 5.0.7 on 2025-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='timing_schedule',
            field=models.JSONField(help_text="List of timings: e.g., ['before_breakfast', 'after_lunch', 'bedtime']"),
        ),
    ]
