# Generated by Django 5.0.7 on 2025-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_timing_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='duration_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('stat', 'STAT (Immediate)'), ('sos', 'SOS (As Needed)')], default='fixed', help_text='Fixed duration, STAT (take immediately), or SOS (as needed)', max_length=10),
        ),
    ]
