"""Runtime integration constants."""

from __future__ import annotations

# Environment variable names
ENV_APPLICATION_VERSION = "APPLICATION_VERSION"
ENV_ENVIRONMENT = "ENVIRONMENT"
ENV_SERVICE_NAME = "SERVICE_NAME"
ENV_AWS_REGION = "AWS_REGION"
ENV_AWS_DEFAULT_REGION = "AWS_DEFAULT_REGION"
ENV_CLOUDWATCH_LOG_GROUP = "CLOUDWATCH_LOG_GROUP"
ENV_CLOUDWATCH_LOG_STREAM = "CLOUDWATCH_LOG_STREAM"
ENV_GIT_COMMIT = "GIT_COMMIT"
ENV_RELEASE_VERSION = "RELEASE_VERSION"
ENV_AWS_ACCOUNT = "AWS_ACCOUNT_ID"
ENV_AVAILABILITY_ZONE = "AWS_AVAILABILITY_ZONE"
ENV_CONTAINER_ID = "HOSTNAME"
ENV_POD_NAME = "POD_NAME"

# Lambda env vars
ENV_LAMBDA_REQUEST_ID = "AWS_REQUEST_ID"
ENV_LAMBDA_FUNCTION_NAME = "AWS_LAMBDA_FUNCTION_NAME"
ENV_LAMBDA_FUNCTION_VERSION = "AWS_LAMBDA_FUNCTION_VERSION"
ENV_LAMBDA_MEMORY = "AWS_LAMBDA_FUNCTION_MEMORY_SIZE"

# Performance target (ms) — soft assert in tests
PERFORMANCE_TARGET_RUNTIME_LINK_MS = 20.0

# CloudWatch console URL template
CLOUDWATCH_CONSOLE_BASE = "https://{region}.console.aws.amazon.com/cloudwatch/home"
