# Generated by Django 5.0.7 on 2026-07-13 03:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(max_length=36)),
                ('request_id', models.CharField(blank=True, max_length=64, null=True)),
                ('workflow_type', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Routing', 'Routing'), ('ReportDelivery', 'Report Delivery'), ('Notification', 'Notification'), ('Payment', 'Payment'), ('WhatsAppFlow', 'WhatsApp Flow'), ('HomeCollection', 'Home Collection'), ('Marketplace', 'Marketplace'), ('Laboratory', 'Laboratory')], max_length=32)),
                ('workflow_instance_id', models.CharField(max_length=36)),
                ('parent_workflow_instance_id', models.CharField(blank=True, max_length=36, null=True)),
                ('sequence_no', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Notification', 'Notification'), ('Booking', 'Booking'), ('Payment', 'Payment'), ('Integration', 'Integration'), ('Routing', 'Routing'), ('Delivery', 'Delivery'), ('Laboratory', 'Laboratory'), ('Marketplace', 'Marketplace')], max_length=32)),
                ('action', models.CharField(choices=[('workflow.started', 'Workflow Started'), ('workflow.queued', 'Workflow Queued'), ('workflow.running', 'Workflow Running'), ('workflow.completed', 'Workflow Completed'), ('workflow.failed', 'Workflow Failed'), ('workflow.retrying', 'Workflow Retrying'), ('workflow.cancelled', 'Workflow Cancelled'), ('workflow.timed_out', 'Workflow Timed Out'), ('workflow.skipped', 'Workflow Skipped')], max_length=64)),
                ('event', models.CharField(max_length=128)),
                ('domain', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=128)),
                ('operation', models.CharField(max_length=128)),
                ('resource_type', models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Order', 'Order'), ('Assignment', 'Assignment'), ('Collection', 'Collection'), ('Report', 'Report'), ('Message', 'Message'), ('Payment', 'Payment'), ('Subscription', 'Subscription'), ('Workflow', 'Workflow')], max_length=32)),
                ('resource_id', models.CharField(max_length=64)),
                ('actor_type', models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient'), ('Admin', 'Admin'), ('System', 'System'), ('Scheduler', 'Scheduler'), ('Celery', 'Celery'), ('Webhook', 'Webhook'), ('Integration', 'Integration')], max_length=32)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('organization_id', models.CharField(max_length=64)),
                ('tenant', models.CharField(blank=True, max_length=64, null=True)),
                ('environment', models.CharField(blank=True, max_length=32, null=True)),
                ('deployment', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Queued', 'Queued'), ('Running', 'Running'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Retrying', 'Retrying'), ('TimedOut', 'Timed Out'), ('Skipped', 'Skipped'), ('Completed', 'Completed')], max_length=16)),
                ('outcome', models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('Partial', 'Partial'), ('Unknown', 'Unknown')], default='Unknown', max_length=16)),
                ('state_before', models.CharField(blank=True, max_length=64, null=True)),
                ('state_after', models.CharField(blank=True, max_length=64, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('max_retry', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('retry_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('external_provider', models.CharField(blank=True, choices=[('Meta', 'Meta'), ('AWS', 'AWS'), ('Razorpay', 'Razorpay'), ('Stripe', 'Stripe'), ('Google', 'Google'), ('Twilio', 'Twilio'), ('SendGrid', 'SendGrid'), ('LocalLab', 'Local Lab'), ('OneMg', '1mg'), ('PharmEasy', 'PharmEasy'), ('Internal', 'Internal')], max_length=32, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_response_code', models.CharField(blank=True, max_length=64, null=True)),
                ('provider_response_message', models.CharField(blank=True, max_length=512, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Business Audit',
                'verbose_name_plural': 'Business Audits',
                'db_table': 'business_audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_instance_id', 'sequence_no'], name='ba_wf_seq_idx'), models.Index(fields=['workflow_instance_id', 'created_at'], name='ba_wf_created_idx'), models.Index(fields=['parent_workflow_instance_id', 'created_at'], name='ba_parent_created_idx'), models.Index(fields=['correlation_id', 'created_at'], name='ba_corr_created_idx'), models.Index(fields=['workflow_type', 'created_at'], name='ba_wftype_created_idx'), models.Index(fields=['provider_reference'], name='ba_provider_ref_idx'), models.Index(fields=['domain', 'created_at'], name='ba_domain_created_idx'), models.Index(fields=['category', 'created_at'], name='ba_category_created_idx'), models.Index(fields=['status', 'created_at'], name='ba_status_created_idx'), models.Index(fields=['resource_type', 'resource_id'], name='ba_resource_idx'), models.Index(fields=['action', 'created_at'], name='ba_action_created_idx'), models.Index(fields=['created_at'], name='ba_created_idx')],
            },
        ),
    ]
