# Generated by Django 5.0.7 on 2026-07-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaudit',
            name='action',
            field=models.CharField(choices=[('workflow.started', 'Workflow Started'), ('workflow.queued', 'Workflow Queued'), ('workflow.running', 'Workflow Running'), ('workflow.completed', 'Workflow Completed'), ('workflow.failed', 'Workflow Failed'), ('workflow.retrying', 'Workflow Retrying'), ('workflow.cancelled', 'Workflow Cancelled'), ('workflow.timed_out', 'Workflow Timed Out'), ('workflow.skipped', 'Workflow Skipped'), ('recommendation.generated', 'Recommendation Generated'), ('recommendation.sent', 'Recommendation Sent'), ('recommendation.delivered', 'Recommendation Delivered'), ('recommendation.read', 'Recommendation Read'), ('recommendation.failed', 'Recommendation Failed'), ('recommendation.retried', 'Recommendation Retried'), ('recommendation.expired', 'Recommendation Expired')], max_length=64),
        ),
    ]
