# Generated by Django 5.0.7 on 2026-07-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_audit", "0002_recommendation_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("workflow.started", "Workflow Started"),
                    ("workflow.queued", "Workflow Queued"),
                    ("workflow.running", "Workflow Running"),
                    ("workflow.completed", "Workflow Completed"),
                    ("workflow.failed", "Workflow Failed"),
                    ("workflow.retrying", "Workflow Retrying"),
                    ("workflow.cancelled", "Workflow Cancelled"),
                    ("workflow.timed_out", "Workflow Timed Out"),
                    ("workflow.skipped", "Workflow Skipped"),
                    ("recommendation.generated", "Recommendation Generated"),
                    ("recommendation.sent", "Recommendation Sent"),
                    ("recommendation.delivered", "Recommendation Delivered"),
                    ("recommendation.read", "Recommendation Read"),
                    ("recommendation.failed", "Recommendation Failed"),
                    ("recommendation.retried", "Recommendation Retried"),
                    ("recommendation.expired", "Recommendation Expired"),
                    ("booking.created", "Booking Created"),
                    ("booking.confirmed", "Booking Confirmed"),
                    ("booking.modified", "Booking Modified"),
                    ("booking.cancelled", "Booking Cancelled"),
                    ("booking.expired", "Booking Expired"),
                    ("booking.closed", "Booking Closed"),
                ],
                max_length=64,
            ),
        ),
    ]
