# Generated by Django 5.0.7 on 2026-07-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business_audit", "0003_booking_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("workflow.started", "Workflow Started"),
                    ("workflow.queued", "Workflow Queued"),
                    ("workflow.running", "Workflow Running"),
                    ("workflow.completed", "Workflow Completed"),
                    ("workflow.failed", "Workflow Failed"),
                    ("workflow.retrying", "Workflow Retrying"),
                    ("workflow.cancelled", "Workflow Cancelled"),
                    ("workflow.timed_out", "Workflow Timed Out"),
                    ("workflow.skipped", "Workflow Skipped"),
                    ("recommendation.generated", "Recommendation Generated"),
                    ("recommendation.sent", "Recommendation Sent"),
                    ("recommendation.delivered", "Recommendation Delivered"),
                    ("recommendation.read", "Recommendation Read"),
                    ("recommendation.failed", "Recommendation Failed"),
                    ("recommendation.retried", "Recommendation Retried"),
                    ("recommendation.expired", "Recommendation Expired"),
                    ("booking.created", "Booking Created"),
                    ("booking.confirmed", "Booking Confirmed"),
                    ("booking.modified", "Booking Modified"),
                    ("booking.cancelled", "Booking Cancelled"),
                    ("booking.expired", "Booking Expired"),
                    ("booking.closed", "Booking Closed"),
                    ("routing.started", "Routing Started"),
                    ("routing.rule_evaluated", "Routing Rule Evaluated"),
                    ("routing.lab_matched", "Routing Lab Matched"),
                    ("routing.price_compared", "Routing Price Compared"),
                    ("routing.discount_applied", "Routing Discount Applied"),
                    ("routing.lab_assigned", "Routing Lab Assigned"),
                    ("routing.failed", "Routing Failed"),
                    ("routing.manual_override", "Routing Manual Override"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="businessaudit",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("Recommendation", "Recommendation"),
                    ("Booking", "Booking"),
                    ("Decision", "Decision"),
                    ("Order", "Order"),
                    ("Assignment", "Assignment"),
                    ("Collection", "Collection"),
                    ("Report", "Report"),
                    ("Message", "Message"),
                    ("Payment", "Payment"),
                    ("Subscription", "Subscription"),
                    ("Workflow", "Workflow"),
                ],
                max_length=32,
            ),
        ),
    ]
