# Generated by Django 5.0.7 on 2026-07-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_audit', '0005_communication_report_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaudit',
            name='resource_type',
            field=models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Decision', 'Decision'), ('Communication', 'Communication'), ('Order', 'Order'), ('Assignment', 'Assignment'), ('Collection', 'Collection'), ('Report', 'Report'), ('Consultation', 'Consultation'), ('Prescription', 'Prescription'), ('Message', 'Message'), ('Payment', 'Payment'), ('Subscription', 'Subscription'), ('Workflow', 'Workflow')], max_length=32),
        ),
        migrations.AlterField(
            model_name='businessaudit',
            name='workflow_type',
            field=models.CharField(choices=[('Recommendation', 'Recommendation'), ('Booking', 'Booking'), ('Routing', 'Routing'), ('ReportDelivery', 'Report Delivery'), ('Consultation', 'Consultation'), ('Prescription', 'Prescription'), ('DiagnosticReport', 'Diagnostic Report'), ('Notification', 'Notification'), ('Payment', 'Payment'), ('WhatsAppFlow', 'WhatsApp Flow'), ('HomeCollection', 'Home Collection'), ('Marketplace', 'Marketplace'), ('Laboratory', 'Laboratory')], max_length=32),
        ),
    ]
