# Generated by Django 5.0.7 on 2026-02-22 14:22

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormulationMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='medicines_f_is_acti_0a029b_idx')],
            },
        ),
        migrations.CreateModel(
            name='FrequencyMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Immutable frequency code (e.g., OD, BD, TDS, QID, SOS)', max_length=50, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('times_per_day', models.PositiveSmallIntegerField(blank=True, help_text='How many times per day', null=True)),
                ('interval_hours', models.PositiveSmallIntegerField(blank=True, help_text='Interval in hours (if applicable)', null=True)),
                ('is_prn', models.BooleanField(default=False, help_text='PRN / SOS usage')),
                ('is_stat', models.BooleanField(default=False, help_text='Immediate one-time dose')),
                ('is_active', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frequency',
                'verbose_name_plural': 'Frequencies',
                'ordering': ['display_name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='medicines_f_search__00bca3_gin'), models.Index(fields=['code'], name='medicines_f_code_89a8dc_idx'), models.Index(fields=['times_per_day'], name='medicines_f_times_p_279042_idx'), models.Index(fields=['is_prn'], name='medicines_f_is_prn_475f24_idx'), models.Index(fields=['is_stat'], name='medicines_f_is_stat_352a2b_idx'), models.Index(fields=['is_active'], name='medicines_f_is_acti_8a21b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='medicines_r_search__c50780_gin'), models.Index(fields=['is_active', 'name'], name='medicines_r_is_acti_fc19a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DrugMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('brand_name', models.CharField(db_index=True, max_length=255)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('composition', models.TextField(blank=True, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('schedule_type', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('is_otc', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drugs', to='medicines.formulationmaster')),
            ],
            options={
                'ordering': ['brand_name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='medicines_d_search__f353f2_gin'), models.Index(fields=['is_active', 'brand_name'], name='medicines_d_is_acti_8d5c17_idx'), models.Index(fields=['generic_name'], name='medicines_d_generic_288aa3_idx'), models.Index(fields=['manufacturer'], name='medicines_d_manufac_8e3abc_idx'), models.Index(fields=['formulation'], name='medicines_d_formula_658cf8_idx')],
            },
        ),
    ]
