# Generated by Django 5.0.7 on 2026-03-21 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseUnitMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='frequencymaster',
            options={'ordering': ['display_name']},
        ),
        migrations.RemoveIndex(
            model_name='drugmaster',
            name='medicines_d_formula_658cf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='frequencymaster',
            name='medicines_f_times_p_279042_idx',
        ),
        migrations.RemoveIndex(
            model_name='frequencymaster',
            name='medicines_f_is_prn_475f24_idx',
        ),
        migrations.RemoveIndex(
            model_name='frequencymaster',
            name='medicines_f_is_stat_352a2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='routemaster',
            name='medicines_r_is_acti_fc19a5_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE EXTENSION IF NOT EXISTS pgcrypto;

                        ALTER TABLE medicines_formulationmaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_frequencymaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_routemaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_drugmaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_drugmaster ADD COLUMN IF NOT EXISTS formulation_uuid uuid;

                        UPDATE medicines_drugmaster d
                        SET formulation_uuid = f.id_uuid
                        FROM medicines_formulationmaster f
                        WHERE d.formulation_id = f.id;

                        DO $$
                        DECLARE
                            fk_name text;
                        BEGIN
                            SELECT conname
                            INTO fk_name
                            FROM pg_constraint
                            WHERE conrelid = 'medicines_drugmaster'::regclass
                              AND confrelid = 'medicines_formulationmaster'::regclass
                              AND contype = 'f'
                            LIMIT 1;

                            IF fk_name IS NOT NULL THEN
                                EXECUTE format('ALTER TABLE medicines_drugmaster DROP CONSTRAINT %I', fk_name);
                            END IF;
                        END $$;

                        ALTER TABLE medicines_formulationmaster DROP CONSTRAINT IF EXISTS medicines_formulationmaster_pkey;
                        ALTER TABLE medicines_formulationmaster DROP COLUMN id;
                        ALTER TABLE medicines_formulationmaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_formulationmaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_formulationmaster ADD CONSTRAINT medicines_formulationmaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_frequencymaster DROP CONSTRAINT IF EXISTS medicines_frequencymaster_pkey;
                        ALTER TABLE medicines_frequencymaster DROP COLUMN id;
                        ALTER TABLE medicines_frequencymaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_frequencymaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_frequencymaster ADD CONSTRAINT medicines_frequencymaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_routemaster DROP CONSTRAINT IF EXISTS medicines_routemaster_pkey;
                        ALTER TABLE medicines_routemaster DROP COLUMN id;
                        ALTER TABLE medicines_routemaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_routemaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_routemaster ADD CONSTRAINT medicines_routemaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_drugmaster DROP CONSTRAINT IF EXISTS medicines_drugmaster_pkey;
                        ALTER TABLE medicines_drugmaster DROP COLUMN id;
                        ALTER TABLE medicines_drugmaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_drugmaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_drugmaster ADD CONSTRAINT medicines_drugmaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_drugmaster DROP COLUMN formulation_id;
                        ALTER TABLE medicines_drugmaster RENAME COLUMN formulation_uuid TO formulation_id;
                        ALTER TABLE medicines_drugmaster ALTER COLUMN formulation_id SET NOT NULL;

                        ALTER TABLE medicines_drugmaster
                            ADD CONSTRAINT medicines_drugmaster_formulation_id_fk
                            FOREIGN KEY (formulation_id)
                            REFERENCES medicines_formulationmaster(id)
                            DEFERRABLE INITIALLY DEFERRED;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='drugmaster',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='formulationmaster',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='frequencymaster',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='routemaster',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='brand_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='schedule_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulationmaster',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='frequencymaster',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='frequencymaster',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='frequencymaster',
            name='interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='frequencymaster',
            name='is_prn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frequencymaster',
            name='is_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='frequencymaster',
            name='times_per_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routemaster',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='routemaster',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='routemaster',
            index=models.Index(fields=['is_active'], name='medicines_r_is_acti_135851_idx'),
        ),
        migrations.AddIndex(
            model_name='doseunitmaster',
            index=models.Index(fields=['is_active'], name='medicines_d_is_acti_732117_idx'),
        ),
    ]
