# Generated by Django 5.0.7 on 2026-03-21 16:58

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_doseunitmaster_alter_frequencymaster_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE EXTENSION IF NOT EXISTS pgcrypto;

                        ALTER TABLE medicines_doseunitmaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_formulationmaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_frequencymaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_routemaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_drugmaster ADD COLUMN IF NOT EXISTS id_uuid uuid DEFAULT gen_random_uuid();
                        ALTER TABLE medicines_drugmaster ADD COLUMN IF NOT EXISTS formulation_uuid uuid;

                        UPDATE medicines_drugmaster d
                        SET formulation_uuid = f.id_uuid
                        FROM medicines_formulationmaster f
                        WHERE d.formulation_id = f.id;

                        DO $$
                        DECLARE
                            fk_name text;
                        BEGIN
                            SELECT conname
                            INTO fk_name
                            FROM pg_constraint
                            WHERE conrelid = 'medicines_drugmaster'::regclass
                              AND confrelid = 'medicines_formulationmaster'::regclass
                              AND contype = 'f'
                            LIMIT 1;

                            IF fk_name IS NOT NULL THEN
                                EXECUTE format('ALTER TABLE medicines_drugmaster DROP CONSTRAINT %I', fk_name);
                            END IF;
                        END $$;

                        ALTER TABLE medicines_doseunitmaster DROP CONSTRAINT IF EXISTS medicines_doseunitmaster_pkey;
                        ALTER TABLE medicines_doseunitmaster DROP COLUMN id;
                        ALTER TABLE medicines_doseunitmaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_doseunitmaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_doseunitmaster ADD CONSTRAINT medicines_doseunitmaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_formulationmaster DROP CONSTRAINT IF EXISTS medicines_formulationmaster_pkey;
                        ALTER TABLE medicines_formulationmaster DROP COLUMN id;
                        ALTER TABLE medicines_formulationmaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_formulationmaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_formulationmaster ADD CONSTRAINT medicines_formulationmaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_frequencymaster DROP CONSTRAINT IF EXISTS medicines_frequencymaster_pkey;
                        ALTER TABLE medicines_frequencymaster DROP COLUMN id;
                        ALTER TABLE medicines_frequencymaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_frequencymaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_frequencymaster ADD CONSTRAINT medicines_frequencymaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_routemaster DROP CONSTRAINT IF EXISTS medicines_routemaster_pkey;
                        ALTER TABLE medicines_routemaster DROP COLUMN id;
                        ALTER TABLE medicines_routemaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_routemaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_routemaster ADD CONSTRAINT medicines_routemaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_drugmaster DROP CONSTRAINT IF EXISTS medicines_drugmaster_pkey;
                        ALTER TABLE medicines_drugmaster DROP COLUMN id;
                        ALTER TABLE medicines_drugmaster RENAME COLUMN id_uuid TO id;
                        ALTER TABLE medicines_drugmaster ALTER COLUMN id SET NOT NULL;
                        ALTER TABLE medicines_drugmaster ADD CONSTRAINT medicines_drugmaster_pkey PRIMARY KEY (id);

                        ALTER TABLE medicines_drugmaster DROP COLUMN formulation_id;
                        ALTER TABLE medicines_drugmaster RENAME COLUMN formulation_uuid TO formulation_id;
                        ALTER TABLE medicines_drugmaster ALTER COLUMN formulation_id SET NOT NULL;

                        ALTER TABLE medicines_drugmaster
                            ADD CONSTRAINT medicines_drugmaster_formulation_id_fk
                            FOREIGN KEY (formulation_id)
                            REFERENCES medicines_formulationmaster(id)
                            DEFERRABLE INITIALLY DEFERRED;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[],
        ),
        migrations.CreateModel(
            name='DrugComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=255)),
                ('strength_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='drugmaster',
            name='drug_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('inhaler', 'Inhaler'), ('drop', 'Drop'), ('cream', 'Cream'), ('insulin', 'Insulin'), ('ointment', 'Ointment'), ('suppository', 'Suppository'), ('supplement', 'Supplement'), ('vaccine', 'Vaccine'), ('other', 'Other')], default='tablet', max_length=20),
        ),
        migrations.AlterField(
            model_name='doseunitmaster',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drugmaster',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='formulationmaster',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routemaster',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='doseunitmaster',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_dose_unit_lower'),
        ),
        migrations.AddConstraint(
            model_name='formulationmaster',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_formulation_lower'),
        ),
        migrations.AddConstraint(
            model_name='routemaster',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_route_lower'),
        ),
        migrations.AddField(
            model_name='drugcomposition',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='medicines.drugmaster'),
        ),
        migrations.AddField(
            model_name='drugcomposition',
            name='strength_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.doseunitmaster'),
        ),
        migrations.AddIndex(
            model_name='drugcomposition',
            index=models.Index(fields=['ingredient'], name='medicines_d_ingredi_ec5b26_idx'),
        ),
    ]
