# Generated by Django 5.0.7 on 2026-04-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_drugcomposition_drugmaster_drug_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='drugcomposition',
            name='medicines_d_ingredi_ec5b26_idx',
        ),
        migrations.AddConstraint(
            model_name='drugcomposition',
            constraint=models.UniqueConstraint(fields=('drug', 'ingredient'), name='unique_ingredient_per_drug'),
        ),
    ]
