# Generated by Django 5.0.7 on 2026-04-05 15:50

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_drugcomposition_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugmaster',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
