# Generated by Django 5.0.7 on 2026-04-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_drugmaster_is_common'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drugmaster',
            new_name='medicines_d_is_acti_1ae5fc_idx',
            old_name='medicines_dr_is_acti_7a8b9c_idx',
        ),
    ]
