# Generated by Django 5.0 — seed RouteMaster / DoseUnitMaster rows used by medicines.services.autofill

from django.db import migrations


def seed_route_masters(apps, schema_editor):
    RouteMaster = apps.get_model("medicines", "RouteMaster")
    # Codes must match medicines.services.autofill.rules.ROUTE_MAP / ALL_ROUTE_CODES.
    rows = [
        ("oral", "oral"),
        ("iv", "iv/im"),
        ("im", "im"),
        ("topical", "topical"),
        ("inhalation", "inhalation"),
        ("sc", "subcutaneous"),
        ("rectal", "rectal"),
        ("other", "other"),
    ]
    for code, name in rows:
        RouteMaster.objects.update_or_create(
            code=code,
            defaults={"name": name, "is_active": True},
        )


def seed_dose_unit_masters(apps, schema_editor):
    DoseUnitMaster = apps.get_model("medicines", "DoseUnitMaster")
    # Names align with ALL_DOSE_UNIT_NAMES / engine lookups (gm aliases to g in rules).
    names = (
        "tablet",
        "ml",
        "g",
        "drops",
        "inhaler",
        "units",
        "suppository",
    )
    for name in names:
        DoseUnitMaster.objects.update_or_create(
            name=name,
            defaults={"is_active": True},
        )


def forwards(apps, schema_editor):
    seed_route_masters(apps, schema_editor)
    seed_dose_unit_masters(apps, schema_editor)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0008_rename_medicines_dr_is_acti_7a8b9c_idx_medicines_d_is_acti_1ae5fc_idx"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
