ENGINE_VERSION = "v1"

RECENT_TEST_WINDOW_DAYS = 7
STRONG_RECENCY_DAYS = 3

DEFAULT_LIMIT_COMMON = 6
DEFAULT_LIMIT_RECOMMENDED = 5
DEFAULT_LIMIT_PACKAGES = 3
DEFAULT_MAX_PER_CATEGORY = 2

MIN_PACKAGE_MATCH_PERCENT = 0.4
MAX_PACKAGE_SIZE = 10

MANDATORY_MIN_SCORE = 0.76

SCORE_WEIGHTS = {
    "clinical": 0.4,
    "doctor": 0.3,
    "global": 0.2,
    "recency": 0.1,
}

