# Generated by Django 5.0.7 on 2026-07-04 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(max_length=36)),
                ('user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('user_role', models.CharField(blank=True, max_length=64, null=True)),
                ('patient_account_id', models.CharField(blank=True, max_length=64, null=True)),
                ('patient_profile_id', models.CharField(blank=True, max_length=64, null=True)),
                ('consultation_id', models.CharField(blank=True, max_length=64, null=True)),
                ('encounter_id', models.CharField(blank=True, max_length=64, null=True)),
                ('module', models.CharField(max_length=64)),
                ('event', models.CharField(max_length=128)),
                ('action', models.CharField(choices=[('authentication.login', 'Authentication Login'), ('authentication.logout', 'Authentication Logout'), ('authentication.failed_login', 'Authentication Failed Login'), ('patient.record_created', 'Patient Record Created'), ('patient.record_updated', 'Patient Record Updated'), ('patient.record_viewed', 'Patient Record Viewed'), ('patient.profile_merged', 'Patient Profile Merged'), ('consultation.started', 'Consultation Started'), ('consultation.completed', 'Consultation Completed'), ('consultation.cancelled', 'Consultation Cancelled'), ('diagnosis.added', 'Diagnosis Added'), ('diagnosis.updated', 'Diagnosis Updated'), ('diagnosis.removed', 'Diagnosis Removed'), ('prescription.generated', 'Prescription Generated'), ('prescription.updated', 'Prescription Updated'), ('prescription.downloaded', 'Prescription Downloaded'), ('prescription.shared', 'Prescription Shared'), ('investigation.added', 'Investigation Added'), ('investigation.updated', 'Investigation Updated'), ('investigation.removed', 'Investigation Removed'), ('recommendation.generated', 'Laboratory Recommendation Generated'), ('recommendation.sent', 'Laboratory Recommendation Sent'), ('report.uploaded', 'Report Uploaded'), ('report.approved', 'Report Approved'), ('report.viewed', 'Report Viewed'), ('report.downloaded', 'Report Downloaded'), ('follow_up.scheduled', 'Follow-up Scheduled'), ('follow_up.completed', 'Follow-up Completed')], max_length=64)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=16)),
                ('resource_type', models.CharField(blank=True, choices=[('patient', 'Patient'), ('consultation', 'Consultation'), ('encounter', 'Encounter'), ('diagnosis', 'Diagnosis'), ('prescription', 'Prescription'), ('investigation', 'Investigation'), ('recommendation', 'Recommendation'), ('report', 'Report'), ('follow_up', 'Follow-up')], max_length=32, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=64, null=True)),
                ('previous_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('system', 'System'), ('doctor', 'Doctor'), ('helpdesk', 'Helpdesk'), ('patient', 'Patient'), ('admin', 'Admin')], default='system', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_information', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clinical Audit',
                'verbose_name_plural': 'Clinical Audits',
                'db_table': 'clinical_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['correlation_id', 'timestamp'], name='ca_corr_ts_idx'), models.Index(fields=['patient_account_id', 'timestamp'], name='ca_patient_ts_idx'), models.Index(fields=['consultation_id', 'timestamp'], name='ca_consult_ts_idx'), models.Index(fields=['encounter_id', 'timestamp'], name='ca_encounter_ts_idx'), models.Index(fields=['user_id', 'timestamp'], name='ca_user_ts_idx'), models.Index(fields=['resource_type', 'resource_id'], name='ca_resource_idx'), models.Index(fields=['action', 'timestamp'], name='ca_action_ts_idx'), models.Index(fields=['timestamp'], name='ca_timestamp_idx')],
            },
        ),
    ]
