# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patientmedicineusage",
            index=models.Index(fields=["patient_id"], name="analytics_p_patient_0a1b2c_idx"),
        ),
    ]
