# Generated by Django 5.0.7 on 2026-04-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_patientmedicineusage_analytics_p_patient_0a1b2c_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patientmedicineusage',
            new_name='analytics_p_patient_26d6cb_idx',
            old_name='analytics_p_patient_0a1b2c_idx',
        ),
    ]
