"""Field lengths and index names for the Business Audit schema."""

CORRELATION_ID_LENGTH = 36
WORKFLOW_INSTANCE_ID_LENGTH = 36
REQUEST_ID_LENGTH = 64
USER_ID_LENGTH = 64
ORGANIZATION_ID_LENGTH = 64
TENANT_LENGTH = 64
ENVIRONMENT_LENGTH = 32
DEPLOYMENT_LENGTH = 64
DOMAIN_LENGTH = 64
SERVICE_LENGTH = 128
OPERATION_LENGTH = 128
EVENT_LENGTH = 128
ACTION_LENGTH = 64
WORKFLOW_TYPE_LENGTH = 32
CATEGORY_LENGTH = 32
STATUS_LENGTH = 16
OUTCOME_LENGTH = 16
STATE_LENGTH = 64
RESOURCE_TYPE_LENGTH = 32
RESOURCE_ID_LENGTH = 64
ACTOR_TYPE_LENGTH = 32
PROVIDER_LENGTH = 32
PROVIDER_REFERENCE_LENGTH = 128
PROVIDER_RESPONSE_CODE_LENGTH = 64
PROVIDER_RESPONSE_MESSAGE_LENGTH = 512
RETRY_REASON_LENGTH = 255

# Django limits index names to 30 characters.
INDEX_WORKFLOW_SEQUENCE = "ba_wf_seq_idx"
INDEX_WORKFLOW_CREATED = "ba_wf_created_idx"
INDEX_PARENT_CREATED = "ba_parent_created_idx"
INDEX_CORRELATION_CREATED = "ba_corr_created_idx"
INDEX_WORKFLOW_TYPE_CREATED = "ba_wftype_created_idx"
INDEX_PROVIDER_REFERENCE = "ba_provider_ref_idx"
INDEX_DOMAIN_CREATED = "ba_domain_created_idx"
INDEX_CATEGORY_CREATED = "ba_category_created_idx"
INDEX_STATUS_CREATED = "ba_status_created_idx"
INDEX_RESOURCE = "ba_resource_idx"
INDEX_ACTION_CREATED = "ba_action_created_idx"
INDEX_CREATED = "ba_created_idx"

# Service-layer limits
MAX_SUMMARY_LENGTH = EVENT_LENGTH
MAX_PAYLOAD_BYTES = 64 * 1024
MAX_REMARKS_LENGTH = 4000
MAX_EXECUTION_TIME_MS = 86_400_000  # 24 hours

# Metadata envelope keys inside new_value
META_KEY = "_meta"
PAYLOAD_KEY = "payload"
