# Generated by Django 5.0.7 on 2025-04-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_appointment_type_and_more'),
        ('clinic', '0003_delete_clinicfrontdeskuser'),
        ('doctor', '0017_alter_doctorfeestructure_unique_together_and_more'),
        ('patient_account', '0008_delete_address'),
        ('queue_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='queue',
            name='queue_manag_doctor__263545_idx',
        ),
        migrations.RemoveIndex(
            model_name='queue',
            name='queue_manag_clinic__140a60_idx',
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['clinic', 'doctor', 'status'], name='queue_manag_clinic__3f9fef_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['clinic', 'position_in_queue'], name='queue_manag_clinic__b2c7b0_idx'),
        ),
    ]
