# Generated by Django 5.0.7 on 2025-03-12 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_appointment_type_and_more'),
        ('doctor', '0017_alter_doctorfeestructure_unique_together_and_more'),
        ('patient_account', '0008_delete_address'),
        ('queue_management', '0002_queue_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='position_in_queue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queue',
            name='estimated_wait_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['doctor', 'status'], name='queue_manag_doctor__263545_idx'),
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['appointment'], name='queue_manag_appoint_d342ea_idx'),
        ),
    ]
