# Generated by Django 5.0.7 on 2025-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0003_queue_position_in_queue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='estimated_wait_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
