# Generated by Django 5.0.7 on 2026-04-28 06:37

from django.db import migrations, models
from django.db.models.functions import TruncDate


def normalize_active_queue_positions(apps, schema_editor):
    Queue = apps.get_model("queue_management", "Queue")
    active_statuses = {"waiting", "vitals_done"}
    rows = (
        Queue.objects.filter(status__in=active_statuses)
        .order_by("doctor_id", "clinic_id", "created_at", "position_in_queue", "id")
        .only("id", "doctor_id", "clinic_id", "created_at", "position_in_queue")
    )
    current_scope = None
    next_position = 1
    batch = []

    for row in rows.iterator():
        scope = (row.doctor_id, row.clinic_id, row.created_at.date())
        if scope != current_scope:
            if batch:
                Queue.objects.bulk_update(batch, ["position_in_queue"])
                batch = []
            current_scope = scope
            next_position = 1
        if row.position_in_queue != next_position:
            row.position_in_queue = next_position
            batch.append(row)
        next_position += 1

    if batch:
        Queue.objects.bulk_update(batch, ["position_in_queue"])


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmenthistory'),
        ('clinic', '0010_clinic_code'),
        ('consultations_core', '0025_rename_clinical_temp_doctor_id_idx_clinical_te_doctor__f25c8d_idx_and_more'),
        ('doctor', '0031_doctor_public_id'),
        ('patient_account', '0010_patient_search_indexes'),
        ('queue_management', '0003_queue_encounter_created_at_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='queue',
            new_name='queue_manag_encount_31d026_idx',
            old_name='queue_manag_encount_d6c510_idx',
        ),
        migrations.AddIndex(
            model_name='queue',
            index=models.Index(fields=['doctor', 'created_at', 'position_in_queue'], name='queue_manag_doctor__38cbc8_idx'),
        ),
        migrations.RunPython(normalize_active_queue_positions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(
                models.F("doctor"),
                models.F("clinic"),
                TruncDate("created_at"),
                models.F("position_in_queue"),
                condition=models.Q(("status__in", ["waiting", "vitals_done"])),
                name="uniq_active_queue_position_per_doctor_clinic_day",
            ),
        ),
    ]
