# Generated by Django 5.0.7 on 2025-03-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0005_remove_queue_estimated_wait_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='wait_time_estimated',
            new_name='estimated_wait_time',
        ),
    ]
