# Generated by Django 5.0.7 on 2025-03-12 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_management', '0007_remove_queue_estimated_wait_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='estimated_wait_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
