# Generated by Django 5.0.7

import labs.utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborganization",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=labs.utils.upload_paths.lab_logo_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="labdocument",
            name="file",
            field=models.FileField(upload_to=labs.utils.upload_paths.lab_document_upload_path),
        ),
    ]
