# Generated by Django 5.0.7 on 2026-05-09 19:48 — amended: data migration + FK repoint + legacy drop.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import connection, migrations, models
from django.utils.text import slugify


def _table_exists(cursor, name: str) -> bool:
    cursor.execute(
        """
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = %s
        """,
        [name],
    )
    return cursor.fetchone() is not None


def sync_legacy_providers_to_labs(apps, schema_editor):
    """Create LabOrganization / LabBranch / LabAddress from legacy diagnostics provider rows (same UUIDs)."""
    if connection.vendor != "postgresql":
        return
    DiagnosticProvider = apps.get_model("diagnostics_engine", "DiagnosticProvider")
    DiagnosticProviderBranch = apps.get_model("diagnostics_engine", "DiagnosticProviderBranch")
    LabOrganization = apps.get_model("labs", "LabOrganization")
    LabBranch = apps.get_model("labs", "LabBranch")
    LabAddress = apps.get_model("labs", "LabAddress")

    for dp in DiagnosticProvider.objects.all():
        slug_base = (slugify(dp.code) or str(dp.id))[:200]
        slug = slug_base
        n = 0
        while LabOrganization.objects.filter(slug=slug).exclude(pk=dp.pk).exists():
            n += 1
            slug = f"{slug_base}-{n}"[:255]

        LabOrganization.objects.update_or_create(
            pk=dp.pk,
            defaults={
                "organization_name": dp.name,
                "display_name": dp.name,
                "organization_code": dp.code,
                "slug": slug,
                "lab_type": "PATHOLOGY_LAB",
                "license_number": dp.license_number or None,
                "owner_name": "System",
                "primary_contact_number": "0000000000",
                "registration_status": "APPROVED",
                "is_verified": True,
                "onboarding_completed": True,
                "is_active_for_orders": bool(dp.is_active),
                "is_active": bool(dp.is_active),
                "is_deleted": bool(dp.deleted_at),
                "deleted_at": dp.deleted_at,
            },
        )

    for dpb in DiagnosticProviderBranch.objects.select_related("provider").all():
        dp = dpb.provider
        global_code = f"{dp.code}-{dpb.branch_code}"[:50]
        while LabBranch.objects.filter(branch_code=global_code).exclude(pk=dpb.pk).exists():
            global_code = (global_code[:40] + uuid.uuid4().hex[:8])[:50]

        LabBranch.objects.update_or_create(
            pk=dpb.pk,
            defaults={
                "organization_id": dp.pk,
                "branch_name": dpb.branch_name,
                "branch_code": global_code,
                "home_collection_available": bool(dpb.home_collection_supported),
                "opening_time": dpb.sample_pickup_start_time,
                "closing_time": dpb.sample_pickup_end_time,
                "is_active": bool(dpb.is_active),
                "is_active_for_orders": bool(dpb.is_active),
                "is_deleted": bool(dpb.deleted_at),
                "deleted_at": dpb.deleted_at,
                "metadata": {},
            },
        )

        lb = LabBranch.objects.get(pk=dpb.pk)
        LabAddress.objects.update_or_create(
            branch=lb,
            defaults={
                "address_line_1": dpb.address_line_1 or "-",
                "address_line_2": dpb.address_line_2,
                "city": dpb.city,
                "state": dpb.state,
                "country": dpb.country or "India",
                "pincode": dpb.pincode,
                "latitude": dpb.latitude,
                "longitude": dpb.longitude,
                "is_active": True,
                "is_deleted": False,
            },
        )


def copy_branch_pricing_rows(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as c:
        if not _table_exists(c, "diagnostics_engine_branchservicepricing"):
            return
        if not _table_exists(c, "labs_branchservicepricing"):
            return
    OldArea = apps.get_model("diagnostics_engine", "BranchServiceArea")
    NewArea = apps.get_model("labs", "BranchServiceArea")
    for row in OldArea.objects.all():
        NewArea.objects.get_or_create(
            pk=row.pk,
            defaults={
                "branch_id": row.branch_id,
                "pincode": row.pincode,
                "is_active": row.is_active,
                "deleted_at": row.deleted_at,
                "deleted_by_id": row.deleted_by_id,
            },
        )

    OldSp = apps.get_model("diagnostics_engine", "BranchServicePricing")
    NewSp = apps.get_model("labs", "BranchServicePricing")
    for row in OldSp.objects.all():
        NewSp.objects.get_or_create(
            pk=row.pk,
            defaults={
                "branch_id": row.branch_id,
                "service_id": row.service_id,
                "selling_price": row.selling_price,
                "cost_price": row.cost_price,
                "platform_margin_snapshot": row.platform_margin_snapshot,
                "doctor_margin_snapshot": row.doctor_margin_snapshot,
                "lab_payout_snapshot": row.lab_payout_snapshot,
                "platform_margin_type": row.platform_margin_type,
                "platform_margin_value": row.platform_margin_value,
                "doctor_commission_type": row.doctor_commission_type,
                "doctor_commission_value": row.doctor_commission_value,
                "valid_from": row.valid_from,
                "valid_to": row.valid_to,
                "is_active": row.is_active,
                "is_available": getattr(row, "is_available", True),
                "deleted_at": row.deleted_at,
                "deleted_by_id": row.deleted_by_id,
            },
        )

    OldPp = apps.get_model("diagnostics_engine", "BranchPackagePricing")
    NewPp = apps.get_model("labs", "BranchPackagePricing")
    for row in OldPp.objects.all():
        NewPp.objects.get_or_create(
            pk=row.pk,
            defaults={
                "branch_id": row.branch_id,
                "package_id": row.package_id,
                "mrp": row.mrp,
                "selling_price": row.selling_price,
                "platform_margin_type": row.platform_margin_type,
                "platform_margin_value": row.platform_margin_value,
                "doctor_commission_type": row.doctor_commission_type,
                "doctor_commission_value": row.doctor_commission_value,
                "lab_payout_snapshot": row.lab_payout_snapshot,
                "commission_source": row.commission_source,
                "settlement_cycle": row.settlement_cycle,
                "fulfillment_mode": row.fulfillment_mode,
                "valid_from": row.valid_from,
                "valid_to": row.valid_to,
                "is_active": row.is_active,
                "is_available": row.is_available,
                "deleted_at": row.deleted_at,
                "deleted_by_id": row.deleted_by_id,
                "created_by_id": row.created_by_id,
                "updated_by_id": row.updated_by_id,
            },
        )


def _drop_fk_to_branch(cursor, table: str):
    cursor.execute(
        """
        SELECT tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.key_column_usage kcu
          ON tc.constraint_schema = kcu.constraint_schema
         AND tc.constraint_name = kcu.constraint_name
        WHERE tc.table_schema = 'public'
          AND tc.table_name = %s
          AND kcu.column_name = 'branch_id'
          AND tc.constraint_type = 'FOREIGN KEY'
        """,
        [table],
    )
    row = cursor.fetchone()
    if row:
        cursor.execute(f'ALTER TABLE "{table}" DROP CONSTRAINT IF EXISTS "{row[0]}"')


def repoint_diagnostic_orders_to_lab_branch(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as c:
        if not _table_exists(c, "diagnostics_engine_diagnosticorder"):
            return
        _drop_fk_to_branch(c, "diagnostics_engine_diagnosticorder")
        c.execute(
            'ALTER TABLE diagnostics_engine_diagnosticorder DROP CONSTRAINT IF EXISTS "diagnostics_engine_diagnosticorder_branch_id_fk_lab"'
        )
        c.execute(
            """
            ALTER TABLE diagnostics_engine_diagnosticorder
            ADD CONSTRAINT diagnostics_engine_diagnosticorder_branch_id_fk_lab
            FOREIGN KEY (branch_id) REFERENCES lab_branches(id)
            DEFERRABLE INITIALLY DEFERRED
            """
        )


def drop_legacy_provider_tables(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as c:
        for tbl in (
            "diagnostics_engine_branchpackagepricing",
            "diagnostics_engine_branchservicepricing",
            "diagnostics_engine_branchservicearea",
            "diagnostics_engine_diagnosticproviderbranch",
            "diagnostics_engine_diagnosticprovider",
        ):
            if _table_exists(c, tbl):
                c.execute(f'DROP TABLE IF EXISTS "{tbl}" CASCADE')


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics_engine", "0005_alter_diagnosticservicemaster_tags"),
        ("labs", "0002_alter_labdocument_file_alter_laborganization_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(sync_legacy_providers_to_labs, migrations.RunPython.noop),
        migrations.CreateModel(
            name="BranchServiceArea",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pincode", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="labs.labbranch",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_branch_service_areas_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_branchservicearea",
            },
        ),
        migrations.CreateModel(
            name="BranchServicePricing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("platform_margin_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("doctor_margin_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("lab_payout_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "platform_margin_type",
                    models.CharField(
                        choices=[("flat", "Flat Amount"), ("percent", "Percentage")],
                        default="flat",
                        max_length=10,
                    ),
                ),
                ("platform_margin_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "doctor_commission_type",
                    models.CharField(
                        choices=[("flat", "Flat Amount"), ("percent", "Percentage")],
                        default="flat",
                        max_length=10,
                    ),
                ),
                ("doctor_commission_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Temporarily hide SKU without deleting pricing history.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_pricing",
                        to="labs.labbranch",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_branch_service_pricing_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_pricing",
                        to="diagnostics_engine.diagnosticservicemaster",
                    ),
                ),
            ],
            options={
                "db_table": "labs_branchservicepricing",
            },
        ),
        migrations.CreateModel(
            name="BranchPackagePricing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=10)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "platform_margin_type",
                    models.CharField(
                        choices=[("flat", "Flat Amount"), ("percent", "Percentage")],
                        default="flat",
                        max_length=10,
                    ),
                ),
                ("platform_margin_value", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "doctor_commission_type",
                    models.CharField(
                        choices=[("flat", "Flat Amount"), ("percent", "Percentage")],
                        default="flat",
                        max_length=10,
                    ),
                ),
                ("doctor_commission_value", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("lab_payout_snapshot", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "commission_source",
                    models.CharField(
                        choices=[("default", "Default"), ("campaign", "Campaign"), ("custom", "Custom")],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("settlement_cycle", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "fulfillment_mode",
                    models.CharField(
                        choices=[("strict", "Strict"), ("partial", "Partial")],
                        default="strict",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateField(default=django.utils.timezone.now)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_pricing",
                        to="labs.labbranch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_branch_package_pricing_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_branch_package_pricing_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_pricing",
                        to="diagnostics_engine.diagnosticpackage",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_branch_package_pricing_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_branchpackagepricing",
                "indexes": [
                    models.Index(fields=["branch"], name="labs_branch_branch__a147db_idx"),
                    models.Index(fields=["package"], name="labs_branch_package_97a92f_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="branchpackagepricing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("branch", "package"),
                name="labs_unique_active_branch_package_pricing",
            ),
        ),
        migrations.AddIndex(
            model_name="branchservicearea",
            index=models.Index(fields=["branch"], name="labs_branch_branch__f63746_idx"),
        ),
        migrations.AddIndex(
            model_name="branchservicearea",
            index=models.Index(fields=["pincode"], name="labs_branch_pincode_1224f4_idx"),
        ),
        migrations.AddConstraint(
            model_name="branchservicearea",
            constraint=models.UniqueConstraint(fields=("branch", "pincode"), name="labs_unique_branch_pincode"),
        ),
        migrations.AddIndex(
            model_name="branchservicepricing",
            index=models.Index(fields=["branch"], name="labs_branch_branch__878873_idx"),
        ),
        migrations.AddIndex(
            model_name="branchservicepricing",
            index=models.Index(fields=["service"], name="labs_branch_service_41ff14_idx"),
        ),
        migrations.AddConstraint(
            model_name="branchservicepricing",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("branch", "service"),
                name="labs_unique_active_branch_service",
            ),
        ),
        migrations.RunPython(copy_branch_pricing_rows, migrations.RunPython.noop),
        migrations.RunPython(repoint_diagnostic_orders_to_lab_branch, migrations.RunPython.noop),
        migrations.RunPython(drop_legacy_provider_tables, migrations.RunPython.noop),
    ]
