# Generated by Django 5.0.7 on 2026-05-10 08:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0006_remove_branchservicearea_branch_and_more'),
        ('labs', '0003_branchservicearea_branchservicepricing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCollectionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_date', models.DateField(db_index=True)),
                ('preferred_slot', models.CharField(max_length=30)),
                ('confirmed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('confirmed_slot', models.CharField(blank=True, max_length=30, null=True)),
                ('collection_status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('COLLECTION_STARTED', 'Collection Started'), ('COLLECTED', 'Collected'), ('FAILED', 'Failed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('address_snapshot', models.JSONField(default=dict, help_text='Immutable patient address snapshot captured at booking time.')),
                ('patient_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'lab_collection_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal operational notes for lab coordination.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'lab_order_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReportDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('delivery_channel', models.CharField(db_index=True, help_text='Channel used for delivery (e.g., WhatsApp, Email).', max_length=30)),
                ('recipient', models.CharField(db_index=True, help_text='Recipient identifier (e.g., phone number, email address).', max_length=20)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('VIEWED', 'Viewed'), ('FAILED', 'Failed')], db_index=True, help_text='Status of the delivery (e.g., sent, delivered, failed).', max_length=30)),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the report was sent.', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Timestamp when the report was delivered.', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the report was viewed by the recipient.', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for delivery failure, if applicable.', null=True)),
                ('external_message_id', models.CharField(blank=True, db_index=True, help_text="External provider's message ID for this delivery.", max_length=255, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of delivery retry attempts.')),
                ('last_retry_at', models.DateTimeField(blank=True, help_text='Timestamp of the last retry attempt.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw provider response payloads or delivery metadata.')),
            ],
            options={
                'db_table': 'lab_report_delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabReportReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=30)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal QA or compliance review notes.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional workflow metadata or AI review payloads.')),
            ],
            options={
                'db_table': 'lab_report_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabSampleTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sample_barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sample_type', models.CharField(max_length=50)),
                ('sample_status', models.CharField(choices=[('COLLECTED', 'Collected'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], db_index=True, default='COLLECTED', max_length=30)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at_lab', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'lab_sample_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabVisitAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_slot', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='PENDING', max_length=30)),
                ('instructions', models.TextField(blank=True, help_text='Patient preparation instructions like fasting requirements.', null=True)),
                ('patient_notes', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'lab_visit_appointments',
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='branchpackagepricing',
            options={'ordering': ['package__name']},
        ),
        migrations.AlterModelOptions(
            name='branchservicearea',
            options={'ordering': ['pincode']},
        ),
        migrations.AlterModelOptions(
            name='branchservicepricing',
            options={'ordering': ['service__name']},
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='home_collection_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='report_delivery_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='is_home_collection_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branchservicearea',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='home_collection_supported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='internal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='report_delivery_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branchpackagepricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='branchpackagepricing',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branchpackagepricing',
            name='doctor_commission_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission paid to doctor (flat or percent).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='branchpackagepricing',
            name='mrp',
            field=models.DecimalField(decimal_places=2, help_text='Maximum Retail Price for the package.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='branchpackagepricing',
            name='platform_margin_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Margin retained by platform per package (flat or percent).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='branchpackagepricing',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Net price offered to the customer for this package.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='branchservicearea',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branchservicepricing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='branchservicepricing',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branchservicepricing',
            name='doctor_commission_value',
            field=models.DecimalField(decimal_places=2, help_text='Commission paid to doctor (flat or percent).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='branchservicepricing',
            name='platform_margin_value',
            field=models.DecimalField(decimal_places=2, help_text='Margin retained by platform per service (flat or percent).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='branchservicepricing',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Net price offered to the customer for this service.', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='branchpackagepricing',
            index=models.Index(fields=['is_active', 'is_available'], name='labs_branch_is_acti_902dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpackagepricing',
            index=models.Index(fields=['valid_from', 'valid_to'], name='labs_branch_valid_f_c1ed40_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservicearea',
            index=models.Index(fields=['city'], name='labs_branch_city_a08409_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservicearea',
            index=models.Index(fields=['state'], name='labs_branch_state_854017_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservicepricing',
            index=models.Index(fields=['is_active', 'is_available'], name='labs_branch_is_acti_0b5c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservicepricing',
            index=models.Index(fields=['valid_from', 'valid_to'], name='labs_branch_valid_f_7f0f9f_idx'),
        ),
        migrations.AddField(
            model_name='labcollectionrequest',
            name='assigned_phlebotomist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_collection_requests', to='labs.labuser'),
        ),
        migrations.AddField(
            model_name='labcollectionrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labcollectionrequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labcollectionrequest',
            name='diagnostic_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_request', to='diagnostics_engine.diagnosticorder'),
        ),
        migrations.AddField(
            model_name='labcollectionrequest',
            name='lab_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_requests', to='labs.labbranch'),
        ),
        migrations.AddField(
            model_name='labcollectionrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_order_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderassignment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborderassignment',
            name='diagnostic_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_assignment', to='diagnostics_engine.diagnosticorder'),
        ),
        migrations.AddField(
            model_name='laborderassignment',
            name='lab_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_orders', to='labs.labbranch'),
        ),
        migrations.AddField(
            model_name='laborderassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreportdeliverylog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreportdeliverylog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreportdeliverylog',
            name='diagnostic_test_report',
            field=models.ForeignKey(help_text='The diagnostic test report associated with this delivery log.', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='diagnostics_engine.diagnostictestreport'),
        ),
        migrations.AddField(
            model_name='labreportdeliverylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreportreview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreportreview',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labreportreview',
            name='diagnostic_test_report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='diagnostics_engine.diagnostictestreport'),
        ),
        migrations.AddField(
            model_name='labreportreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to='labs.labuser'),
        ),
        migrations.AddField(
            model_name='labreportreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labsampletracking',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_samples', to='labs.labuser'),
        ),
        migrations.AddField(
            model_name='labsampletracking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labsampletracking',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labsampletracking',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_samples', to='labs.labuser'),
        ),
        migrations.AddField(
            model_name='labsampletracking',
            name='test_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample_tracking', to='diagnostics_engine.diagnosticordertestline'),
        ),
        migrations.AddField(
            model_name='labsampletracking',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labvisitappointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labvisitappointment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labvisitappointment',
            name='diagnostic_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_appointment', to='diagnostics_engine.diagnosticorder'),
        ),
        migrations.AddField(
            model_name='labvisitappointment',
            name='lab_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_appointments', to='labs.labbranch'),
        ),
        migrations.AddField(
            model_name='labvisitappointment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='labcollectionrequest',
            index=models.Index(fields=['collection_status'], name='lab_collect_collect_90a0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='labcollectionrequest',
            index=models.Index(fields=['preferred_date'], name='lab_collect_preferr_f8fcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='labcollectionrequest',
            index=models.Index(fields=['confirmed_date'], name='lab_collect_confirm_f2f28d_idx'),
        ),
        migrations.AddIndex(
            model_name='labcollectionrequest',
            index=models.Index(fields=['lab_branch'], name='lab_collect_lab_bra_281634_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderassignment',
            index=models.Index(fields=['status'], name='lab_order_a_status_910963_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderassignment',
            index=models.Index(fields=['lab_branch'], name='lab_order_a_lab_bra_b9b8bc_idx'),
        ),
        migrations.AddIndex(
            model_name='laborderassignment',
            index=models.Index(fields=['assigned_at'], name='lab_order_a_assigne_001446_idx'),
        ),
        migrations.AddIndex(
            model_name='labreportdeliverylog',
            index=models.Index(fields=['delivery_status'], name='lab_report__deliver_e1a20c_idx'),
        ),
        migrations.AddIndex(
            model_name='labreportdeliverylog',
            index=models.Index(fields=['recipient'], name='lab_report__recipie_6fb353_idx'),
        ),
        migrations.AddIndex(
            model_name='labreportdeliverylog',
            index=models.Index(fields=['delivery_channel'], name='lab_report__deliver_29ee7e_idx'),
        ),
        migrations.AddIndex(
            model_name='labreportdeliverylog',
            index=models.Index(fields=['external_message_id'], name='lab_report__externa_f99098_idx'),
        ),
        migrations.AddIndex(
            model_name='labreportreview',
            index=models.Index(fields=['review_status'], name='lab_report__review__5c92c5_idx'),
        ),
        migrations.AddIndex(
            model_name='labreportreview',
            index=models.Index(fields=['reviewed_at'], name='lab_report__reviewe_a4b4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='labreportreview',
            index=models.Index(fields=['approved_at'], name='lab_report__approve_a3a34d_idx'),
        ),
        migrations.AddIndex(
            model_name='labsampletracking',
            index=models.Index(fields=['sample_barcode'], name='lab_sample__sample__2d8ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='labsampletracking',
            index=models.Index(fields=['sample_status'], name='lab_sample__sample__08d50b_idx'),
        ),
        migrations.AddIndex(
            model_name='labsampletracking',
            index=models.Index(fields=['collected_at'], name='lab_sample__collect_2730c3_idx'),
        ),
        migrations.AddIndex(
            model_name='labsampletracking',
            index=models.Index(fields=['received_at_lab'], name='lab_sample__receive_1394d6_idx'),
        ),
        migrations.AddIndex(
            model_name='labvisitappointment',
            index=models.Index(fields=['status'], name='lab_visit_a_status_99faec_idx'),
        ),
        migrations.AddIndex(
            model_name='labvisitappointment',
            index=models.Index(fields=['appointment_date'], name='lab_visit_a_appoint_67de27_idx'),
        ),
        migrations.AddIndex(
            model_name='labvisitappointment',
            index=models.Index(fields=['lab_branch'], name='lab_visit_a_lab_bra_1bd3d4_idx'),
        ),
    ]
