# Generated by Django 5.0.7 on 2026-05-17 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0011_rename_diagnostics_routing_order_status_idx_diagnostics_routing_c84008_idx_and_more'),
        ('labs', '0004_labcollectionrequest_laborderassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrderTestExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled'), ('sample_collected', 'Sample Collected'), ('in_processing', 'In Processing'), ('report_ready', 'Report Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('no_show', 'No Show'), ('unsupported', 'Unsupported')], db_index=True, default='pending', max_length=30)),
                ('execution_type', models.CharField(choices=[('home_collection', 'Home Collection'), ('branch_visit', 'Branch Visit')], default='branch_visit', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('sample_collected_at', models.DateTimeField(blank=True, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('report_ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_test_executions', to=settings.AUTH_USER_MODEL)),
                ('assigned_phlebotomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_test_executions', to='labs.labuser')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='labs.laborderassignment')),
                ('collection_request', models.ForeignKey(blank=True, help_text='Associated home collection workflow for this test execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='labs.labcollectionrequest')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('lab_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_executions', to='labs.labbranch')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_test_executions', to=settings.AUTH_USER_MODEL)),
                ('test_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_test_executions', to='diagnostics_engine.diagnosticordertestline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('visit_appointment', models.ForeignKey(blank=True, help_text='Associated branch visit workflow for this test execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='labs.labvisitappointment')),
            ],
            options={
                'db_table': 'lab_order_test_executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['execution_status'], name='lab_order_t_executi_39bfd3_idx'), models.Index(fields=['lab_branch'], name='lab_order_t_lab_bra_87b26e_idx'), models.Index(fields=['collection_request'], name='lab_order_t_collect_58a5fc_idx'), models.Index(fields=['visit_appointment'], name='lab_order_t_visit_a_ce109f_idx'), models.Index(fields=['scheduled_at'], name='lab_order_t_schedul_9e8632_idx'), models.Index(fields=['assignment'], name='lab_order_t_assignm_5a4c74_idx'), models.Index(fields=['test_line'], name='lab_order_t_test_li_9aa191_idx'), models.Index(fields=['execution_type'], name='lab_order_t_executi_37fb67_idx'), models.Index(fields=['accepted_at'], name='lab_order_t_accepte_dbd2f7_idx'), models.Index(fields=['completed_at'], name='lab_order_t_complet_85e58d_idx')],
            },
        ),
    ]
