# Generated by Django 5.0.7 on 2026-05-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0007_lab_workflow_db_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcollectionrequest',
            name='collection_type',
            field=models.CharField(db_index=True, default='HOME', help_text='Logistics channel snapshot, e.g. HOME, PARTNER, CAMP.', max_length=20),
        ),
    ]
