# Generated by Django 5.0.7 on 2025-04-26 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0017_alter_doctorfeestructure_unique_together_and_more'),
        ('patient_account', '0008_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_pnr', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('prescription_pnr', models.CharField(db_index=True, editable=False, max_length=10, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doctor.doctor')),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patient_account.patientaccount')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patient_account.patientprofile')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-started_at'],
            },
        ),
    ]
