# Generated by Django 5.0.7 on 2025-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advicetemplate',
            name='description',
            field=models.CharField(help_text='Predefined lifestyle/dietary advice', max_length=500, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='complaint',
            unique_together={('consultation', 'complaint_text')},
        ),
    ]
