# Generated by Django 5.0.7 on 2025-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_alter_advicetemplate_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='advice',
            constraint=models.UniqueConstraint(fields=('consultation', 'custom_advice'), name='unique_custom_advice_per_consultation'),
        ),
    ]
