# Generated by Django 5.0.7 on 2025-04-27 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models
from utils.static_data_service import StaticDataService


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, help_text='ICD-10/11 code (optional)', max_length=20, null=True)),
                ('description', models.CharField(help_text='Diagnosis description', max_length=500)),
                ('location', models.CharField(blank=True, choices=StaticDataService.get_location_choices(), help_text='Diagnosis location in body', max_length=20, null=True)),
                ('diagnosis_type', models.CharField(choices=StaticDataService.get_diagnosis_type_choices(), default='confirmed', help_text='Type of diagnosis', max_length=20)),
                ('is_general', models.BooleanField(default=False, help_text='Selected from predefined general diagnosis list')),
                ('doctor_note', models.TextField(blank=True, help_text='Internal notes for doctor', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='consultations.consultation')),
            ],
            options={
                'verbose_name': 'Diagnosis',
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['created_at'],
            },
        ),
    ]
