# Generated by Django 5.0.7 on 2025-04-27 07:49

from django.db import migrations
from utils.static_data_service import StaticDataService

def fix_diagnosis_location(apps, schema_editor):
    Diagnosis = apps.get_model('diagnosis', 'Diagnosis')
    for diagnosis in Diagnosis.objects.all():
        if diagnosis.location not in [choice[0] for choice in StaticDataService.get_location_choices()]:
            diagnosis.location = None  # Or set a default value
            diagnosis.save()
class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_diagnosis'),
    ]

    operations = [
    ]
