# Generated by Django 5.0.7 on 2025-04-28 07:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20250427_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Predefined lifestyle/dietary advice', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advice Template',
                'verbose_name_plural': 'Advice Templates',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_advice', models.TextField(blank=True, help_text='Custom lifestyle/dietary advice', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='consultations.consultation')),
                ('advice_templates', models.ManyToManyField(blank=True, related_name='custom_advices', to='consultations.advicetemplate')),
            ],
            options={
                'verbose_name': 'Advice',
                'verbose_name_plural': 'Advices',
                'ordering': ['created_at'],
            },
        ),
    ]
