# Generated by Django 5.0.7 on 2025-04-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_advicetemplate_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='closure_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription_pdf',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
