# Generated by Django 5.0.7 on 2025-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultation_closure_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='prescription_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='prescriptions/'),
        ),
    ]
