# Generated by Django 5.0.7 on 2025-06-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_alter_consultation_prescription_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Mark consultation as important'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='tag',
            field=models.CharField(blank=True, choices=[('follow_up', 'Follow-Up'), ('critical', 'Critical'), ('review', 'Review')], help_text='Optional tag like Follow-Up, Critical, etc.', max_length=50, null=True),
        ),
    ]
