# Generated by Django 5.0.7 on 2026-02-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_clinicalencounter_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalencounter',
            name='prescription_pnr',
        ),
    ]
