# Generated by Django 5.0.7 on 2025-06-11 11:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_consultation_is_important_consultation_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5')),
                ('comments', models.TextField(blank=True, help_text='Optional comment by patient', null=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text="Hide patient's identity if True")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_feedback', to='consultations.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient Feedback',
                'verbose_name_plural': 'Patient Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
