# Generated by Django 5.0.7 on 2026-02-15 13:02
# id kept as BigAutoField to match existing DB; only unique_together and other alters applied

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_clinic_code'),
        ('consultations', '0011_add_encounterdailycounter_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterdailycounter',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counters', to='clinic.clinic'),
        ),
        migrations.AlterField(
            model_name='encounterdailycounter',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='encounterdailycounter',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='encounterdailycounter',
            unique_together={('clinic', 'date')},
        ),
    ]
