# Generated by Django 5.0.7 on 2026-02-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_alter_encounterdailycounter_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterdailycounter',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
