# Generated by Django 5.0.7 on 2026-02-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_clinic_code'),
        ('consultations', '0013_alter_encounterdailycounter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalencounter',
            name='consultation_pnr',
        ),
        # clinic_id already exists in DB; only add to migration state
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='clinicalencounter',
                    name='clinic',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='clinic.clinic'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='visit_pnr',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Format: YYMMDD-CL-XXXXX-XXX', max_length=30, null=True, unique=True),
        ),
    ]
