# Generated by Django 5.0.7 on 2026-02-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_add_clinicalencounter_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalencounter',
            name='visit_pnr',
            field=models.CharField(db_index=True, editable=False, help_text='Format: YYMMDD-CL-XXXXX-XXX', max_length=30, unique=True),
        ),
    ]
