# Generated by Django 5.0.7 on 2026-02-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_clinic_code'),
        ('consultations', '0015_alter_clinicalencounter_visit_pnr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounterdailycounter',
            name='is_active',
        ),
        migrations.AddIndex(
            model_name='encounterdailycounter',
            index=models.Index(fields=['clinic', 'date'], name='consultatio_clinic__99f96c_idx'),
        ),
    ]
