# Generated by Django 5.0.7 on 2026-02-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0016_remove_encounterdailycounter_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalencounter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clinical Encounter', 'verbose_name_plural': 'Clinical Encounters'},
        ),
    ]
