from .report_constants import (
    APPOINTMENT_TYPE_CHOICES,
    DAILY_TRENDS_DAYS,
    INSIGHT_THRESHOLDS,
    MONTHLY_TRENDS_MONTHS,
    RECENT_APPOINTMENTS_LIMIT,
    STATUS_CHOICES,
)

__all__ = [
    "APPOINTMENT_TYPE_CHOICES",
    "STATUS_CHOICES",
    "INSIGHT_THRESHOLDS",
    "RECENT_APPOINTMENTS_LIMIT",
    "DAILY_TRENDS_DAYS",
    "MONTHLY_TRENDS_MONTHS",
]
