# Generated by Django 5.0.7 on 2025-07-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
