# Generated by Django 5.0.7 on 2025-02-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0002_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorConnection',
        ),
    ]
