# Generated by Django 5.0.7 on 2026-01-03 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0002_patientaccount_is_active_patientprofile_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='onboarding_source',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('clinic', 'Clinic Staff'), ('self', 'Self Registration')], default='self', max_length=20),
        ),
    ]
