# Generated by Django 5.0.7 on 2026-01-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0003_patientaccount_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
