# Generated by Django 5.0.7 on 2025-02-21 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0004_medicalhistory_created_at_medicalhistory_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='relation',
            field=models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('father', 'Father'), ('mother', 'Mother'), ('child', 'Child')], default='self', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='PatientProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='patient_account.patientprofile')),
            ],
        ),
    ]
