# Generated by Django 5.0.7 on 2025-02-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0005_remove_patientprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofiledetails',
            name='address',
        ),
    ]
