# Generated by Django 5.0.7 on 2026-01-03 17:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0005_alter_patientaccount_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 3, 17, 32, 23, 604949, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2026, 1, 3, 17, 32, 47, 202363, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
