# Generated by Django 5.0.7 on 2026-02-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0006_alter_patientaccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
