# Generated by Django 5.0.7 on 2025-02-27 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0007_patientaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
