# Generated by Django 5.0.7 on 2026-04-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0007_patientprofile_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
