# Generated by Django 5.0.7 on 2026-04-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_account', '0008_alter_patientprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='age_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
