"""Support API error codes."""

INVALID_IDENTIFIER = "INVALID_IDENTIFIER"
WORKFLOW_NOT_FOUND = "WORKFLOW_NOT_FOUND"
PERMISSION_DENIED = "PERMISSION_DENIED"
INVESTIGATION_FAILED = "INVESTIGATION_FAILED"
NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
VALIDATION_ERROR = "VALIDATION_ERROR"
