# Generated by Django 5.0.7 on 2025-01-14 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a custom specialization', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Provide a description if needed', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='hospitals',
        ),
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, help_text='Short description displayed to patients', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinics',
            field=models.ManyToManyField(related_name='doctors', to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qualification', models.CharField(help_text='e.g., MBBS, MD', max_length=255)),
                ('institute', models.CharField(help_text='Name of the institution', max_length=255)),
                ('year_of_completion', models.PositiveIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan_card_number', models.CharField(max_length=10, unique=True)),
                ('aadhar_card_number', models.CharField(max_length=12, unique=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government_ids', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medical_registration_number', models.CharField(max_length=50, unique=True)),
                ('medical_council', models.CharField(help_text='e.g., Medical Council of India', max_length=255)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialization', models.CharField(blank=True, choices=[('CL', 'Cardiologist'), ('DL', 'Dermatologist'), ('EMC', 'Emergency Medicine Specialist'), ('IL', 'Immunologist'), ('AL', 'Anesthesiologist'), ('CRS', 'Colon and Rectal Surgeon'), ('END', 'Endocrinologist'), ('GAS', 'Gastroenterologist'), ('HIM', 'Hematologist'), ('ONC', 'Oncologist'), ('NEU', 'Neurologist'), ('NS', 'Neurosurgeon'), ('PED', 'Pediatrician'), ('PLS', 'Plastic Surgeon'), ('PMR', 'Physical Medicine and Rehabilitation Specialist'), ('PSY', 'Psychiatrist'), ('RAD', 'Radiologist'), ('RHU', 'Rheumatologist'), ('THS', 'Thoracic Surgeon'), ('URO', 'Urologist'), ('ENT', 'Otorhinolaryngologist (ENT Specialist)'), ('OPH', 'Ophthalmologist'), ('MFS', 'Maternal-Fetal Medicine Specialist'), ('NEON', 'Neonatologist'), ('GYN', 'Gynecologist'), ('ORT', 'Orthopedic Surgeon'), ('VCS', 'Vascular Surgeon'), ('IMM', 'Allergy and Immunology Specialist'), ('PAIN', 'Pain Medicine Specialist'), ('PATH', 'Pathologist'), ('NM', 'Nuclear Medicine Specialist'), ('SLE', 'Sleep Medicine Specialist'), ('OT', 'Occupational Medicine Specialist'), ('SM', 'Sports Medicine Specialist'), ('PS', 'Palliative Medicine Specialist'), ('DER', 'Dermatosurgeon'), ('FM', 'Family Medicine Specialist'), ('GEN', 'General Practitioner'), ('GER', 'Geriatrician'), ('ID', 'Infectious Disease Specialist'), ('TOX', 'Toxicologist'), ('GENS', 'General Surgeon'), ('TRS', 'Transplant Surgeon'), ('CRIT', 'Critical Care Specialist'), ('COS', 'Cosmetic Surgeon'), ('LAB', 'Lab Medicine Specialist'), ('CLG', 'Clinical Geneticist')], max_length=5, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates if this is the primary displayed specialization')),
                ('custom_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specializations', to='doctor.customspecialization')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='doctor.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorAdditionalDetails',
        ),
    ]
