# Generated by Django 5.0.7 on 2025-06-21 06:55

import doctor.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=doctor.utils.uploads.doctor_photo_upload_path),
        ),
    ]
