# Generated by Django 5.0.7 on 2025-06-21 12:40

import doctor.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to=doctor.utils.uploads.doctor_kyc_upload_path),
        ),
    ]
