# Generated by Django 5.0.7 on 2025-06-21 15:53

import doctor.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_registration_registration_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=doctor.utils.uploads.doctor_education_upload_path),
        ),
    ]
