# Generated by Django 5.0.7 on 2025-01-16 19:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_customspecialization_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', help_text='Name of the award', max_length=255)),
                ('description', models.TextField(blank=True, default='NA', help_text='Details about the award', null=True)),
                ('awarded_by', models.CharField(default='NA', help_text='Organization granting the award', max_length=255)),
                ('date_awarded', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='NA', help_text='Certification title (e.g., Fellowship in Cardiology)', max_length=255)),
                ('issued_by', models.CharField(default='NA', help_text='Organization issuing the certification', max_length=255)),
                ('date_of_issue', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Leave blank if no expiry', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NA', help_text='Service name (e.g., Angioplasty, Skin Treatment)', max_length=255)),
                ('description', models.TextField(blank=True, default='NA', help_text='Details about the service', null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Fee for the service', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='doctor.doctor')),
            ],
        ),
    ]
