# Generated by Django 5.0.7 on 2025-06-21 16:48

import doctor.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_education_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentid',
            name='aadhar_card_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.utils.uploads.aadhar_card_upload_path),
        ),
        migrations.AddField(
            model_name='governmentid',
            name='pan_card_file',
            field=models.FileField(blank=True, null=True, upload_to=doctor.utils.uploads.pan_card_upload_path),
        ),
    ]
