# Generated by Django 5.0.7 on 2025-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_governmentid_aadhar_card_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='kyc_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
