# Generated by Django 5.0.7 on 2025-01-16 19:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_award_created_at_alter_award_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5')),
                ('comments', models.TextField(blank=True, default='NA', help_text='Feedback from the reviewer', null=True)),
                ('reviewed_by', models.CharField(default='NA', help_text='Name of the patient/clinic (optional)', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='NA', help_text='e.g., English, Hindi, Marathi', max_length=50)),
                ('proficiency', models.CharField(choices=[('Basic', 'Basic'), ('Fluent', 'Fluent'), ('Native', 'Native')], default='Fluent', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(default='NA', help_text='e.g., LinkedIn, ResearchGate', max_length=50)),
                ('url', models.URLField(default='NA', help_text='Link to the profile')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='doctor.doctor')),
            ],
        ),
    ]
