# Generated by Django 5.0.7 on 2025-06-21 17:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctor_kyc_completed_doctor_kyc_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('registration_reason', models.TextField(blank=True, null=True)),
                ('education_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('education_reason', models.TextField(blank=True, null=True)),
                ('photo_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('photo_reason', models.TextField(blank=True, null=True)),
                ('aadhar_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('aadhar_reason', models.TextField(blank=True, null=True)),
                ('pan_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('pan_reason', models.TextField(blank=True, null=True)),
                ('kya_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_status', to='doctor.doctor')),
            ],
        ),
    ]
