# Generated by Django 5.0.7 on 2025-06-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_kycstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_modes',
            field=models.JSONField(default=list, help_text="Available consultation modes (e.g., ['video', 'in_clinic'])"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured in search results'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_spoken',
            field=models.JSONField(default=list, help_text='Languages the doctor can speak'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='primary_specialization',
            field=models.CharField(default='General', help_text='Primary specialization for indexing/search', max_length=100),
        ),
    ]
