# Generated by Django 5.0.7 on 2025-02-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_remove_doctor_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
    ]
