# Generated by Django 5.0.7 on 2025-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('doctor', '0011_doctoravailability_doctorfeestructure_doctorleave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='doctorfeestructure',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='followuppolicy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='doctoropdstatus',
            index=models.Index(fields=['doctor'], name='doctor_doct_doctor__ef25e5_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoropdstatus',
            index=models.Index(fields=['clinic'], name='doctor_doct_clinic__c78456_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoropdstatus',
            index=models.Index(fields=['is_available'], name='doctor_doct_is_avai_ebc734_idx'),
        ),
    ]
