# Generated by Django 5.0.7 on 2025-02-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_remove_doctor_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='mobile_number',
            new_name='secondary_mobile_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='mobile',
        ),
    ]
