# Generated by Django 5.0.7 on 2025-02-26 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_rename_mobile_number_doctor_secondary_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(default='NA', max_length=255)),
                ('address2', models.TextField(default='NA', max_length=255)),
                ('city', models.CharField(default='NA', max_length=100)),
                ('state', models.CharField(default='NA', max_length=100)),
                ('pincode', models.CharField(default='NA', max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('google_maps_url', models.URLField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='doctor.doctor')),
            ],
        ),
    ]
