# Generated by Django 5.0.7 on 2025-09-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_doctor_digital_signature_consent_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consent_for_data_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='terms_and_conditions_acceptance',
            field=models.BooleanField(default=False),
        ),
    ]
