# Generated by Django 5.0.7 on 2025-02-27 07:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_delete_clinicfrontdeskuser'),
        ('doctor', '0015_delete_doctorlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10), default=list, size=None)),
                ('morning_start', models.TimeField(blank=True, null=True)),
                ('morning_end', models.TimeField(blank=True, null=True)),
                ('evening_start', models.TimeField(blank=True, null=True)),
                ('evening_end', models.TimeField(blank=True, null=True)),
                ('night_start', models.TimeField(blank=True, null=True)),
                ('night_end', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, help_text='Lunch/Personal Break Start Time', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Lunch/Personal Break End Time', null=True)),
                ('slot_duration', models.PositiveIntegerField(default=15, help_text='Consultation duration per patient (in minutes)')),
                ('buffer_time', models.PositiveIntegerField(default=5, help_text='Gap between two appointments (in minutes)')),
                ('max_appointments_per_day', models.PositiveIntegerField(default=20, help_text='Daily appointment limit')),
                ('emergency_slots', models.PositiveIntegerField(default=2, help_text='Reserved slots for emergency cases')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time_consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('follow_up_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case_paper_duration', models.PositiveIntegerField(help_text='Case paper validity in days')),
                ('case_paper_renewal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emergency_consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('online_consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rescheduling_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic')},
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(help_text='Date when the doctor is unavailable')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for leave', null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'leave_date')},
            },
        ),
        migrations.CreateModel(
            name='FollowUpPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_duration', models.PositiveIntegerField(help_text='Follow-up validity in days (e.g., 7, 15, 30)')),
                ('follow_up_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_follow_up_visits', models.PositiveIntegerField(default=1, help_text='Maximum follow-ups allowed in duration')),
                ('allow_online_follow_up', models.BooleanField(default=True, help_text='Can follow-up be done online?')),
                ('online_follow_up_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('access_past_appointments', models.BooleanField(default=True, help_text='Can doctor view past visits?')),
                ('access_past_prescriptions', models.BooleanField(default=True, help_text='Can doctor view old prescriptions?')),
                ('access_past_reports', models.BooleanField(default=True, help_text='Can doctor view test reports?')),
                ('access_other_clinic_history', models.BooleanField(default=False, help_text='Can doctor see history from other clinics?')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
