# Generated by Django 5.0.7 on 2025-02-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_doctoravailability_doctorfeestructure_doctorleave_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorfeestructure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorfeestructure',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctorfeestructure',
            name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='doctorleave',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='doctorleave',
            name='doctor',
        ),
        migrations.AlterUniqueTogether(
            name='followuppolicy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='followuppolicy',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='followuppolicy',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.DeleteModel(
            name='DoctorFeeStructure',
        ),
        migrations.DeleteModel(
            name='DoctorLeave',
        ),
        migrations.DeleteModel(
            name='FollowUpPolicy',
        ),
    ]
