# Generated by Django 5.0.7 on 2025-09-27 08:23

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_doctor_rejection_reason_doctor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_modes',
            field=models.JSONField(default=doctor.models.default_consultation_modes, help_text="Available consultation modes (e.g., ['video', 'in_clinic'])"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='languages_spoken',
            field=models.JSONField(default=doctor.models.default_languages_spoken, help_text='Languages the doctor can speak'),
        ),
    ]
