# Generated by Django 5.0.7 on 2025-10-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_doctor_consultation_modes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='secondary_mobile_number',
            field=models.CharField(default='NA', max_length=15),
        ),
    ]
