# Generated by Django 5.0.7 on 2025-05-29 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_doctorfeestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentid',
            name='aadhar_card_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Aadhar number.', regex='^[0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='governmentid',
            name='pan_card_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN format.', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')]),
        ),
    ]
