# Generated by Django 5.0.7 on 2025-05-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_alter_governmentid_aadhar_card_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('doctor', 'qualification', 'institute', 'year_of_completion')},
        ),
    ]
