# Generated by Django 5.0.7 on 2025-06-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_alter_education_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customspecialization',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='customspecialization',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together={('doctor', 'specialization', 'custom_specialization')},
        ),
    ]
