# Generated by Django 5.0.7 on 2025-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0019_doctor_profile_completion_doctor_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_verification_Badges',
            field=models.JSONField(default=list, help_text='List of badges earned by the doctor'),
        ),
        migrations.AddField(
            model_name='kycstatus',
            name='digital_signature',
            field=models.FileField(blank=True, null=True, upload_to='digital_signature/'),
        ),
    ]
