# Generated by Django 5.0.7 on 2025-10-12 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_doctor_profile_verification_badges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(help_text='e.g., Indian Medical Association (IMA)', max_length=255)),
                ('membership_id', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, help_text='e.g., Life Member, Fellow', max_length=100, null=True)),
                ('year_of_joining', models.PositiveIntegerField(blank=True, null=True)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='doctor/memberships/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='doctor.doctor')),
            ],
            options={
                'ordering': ['organization_name'],
            },
        ),
    ]
