# Generated by Django 5.0.7 on 2025-06-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_customspecialization_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorservice',
            unique_together={('doctor', 'name')},
        ),
    ]
