# Generated by Django 5.0.7 on 2025-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0021_alter_doctorservice_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Medical Registration', 'verbose_name_plural': 'Medical Registrations'},
        ),
        migrations.AddField(
            model_name='registration',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin verified medical license?'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor_registration_certificates/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='valid_upto',
            field=models.DateField(blank=True, help_text='License expiry date if applicable', null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('doctor',), name='unique_doctor_registration'),
        ),
    ]
