# Generated by Django 5.0.7 on 2025-10-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_doctorbankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_progress',
            field=models.IntegerField(default=0),
        ),
    ]
