# Generated by Django 5.0.7 on 2025-12-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_doctor_profile_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_verification_Badges',
            field=models.JSONField(blank=True, default=list, help_text='List of badges earned by the doctor', null=True),
        ),
    ]
