# Generated by Django 5.0.7 on 2025-12-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_alter_doctor_profile_verification_badges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-year_of_completion', '-created_at']},
        ),
    ]
