# Generated by Django 5.0.7 on 2025-12-25 05:51

import doctor.utils.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_alter_education_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycstatus',
            name='digital_signature',
            field=models.FileField(blank=True, null=True, upload_to=doctor.utils.uploads.digital_signature_upload_path),
        ),
    ]
