# Generated by Django 5.0.7 on 2025-12-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0026_alter_kycstatus_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='followuppolicy',
            name='allow_free_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='followuppolicy',
            name='auto_apply_case_paper',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='followuppolicy',
            name='free_follow_up_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
