# Generated by Django 5.0.7 on 2025-12-27 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinicprofile'),
        ('doctor', '0027_followuppolicy_allow_free_follow_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorfeestructure',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorfeestructure',
            name='night_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorfeestructure',
            name='night_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorfeestructure',
            name='night_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_cancellation', models.BooleanField(default=True)),
                ('cancellation_window_hours', models.PositiveIntegerField(help_text='Before appointment')),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allow_refund', models.BooleanField(default=False)),
                ('refund_percentage', models.PositiveIntegerField(default=0)),
                ('rescheduling_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
