# Generated by Django 5.0.7 on 2025-12-28 19:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_doctorfeestructure_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorbankdetails',
            name='verified',
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='masked_account_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('penny_drop', 'Penny Drop'), ('upi', 'UPI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorbankdetails',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_bank_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorbankdetails',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorbankdetails',
            name='ifsc_code',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='doctorbankdetails',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Invalid UPI ID', regex='^[\\w.-]+@[\\w.-]+$')]),
        ),
    ]
