# Generated by Django 5.0.7 on 2025-12-30 10:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_clinic_emergency_contact_name_and_more'),
        ('doctor', '0029_remove_doctorbankdetails_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedulingRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allow_same_day_appointments', models.BooleanField(default=True)),
                ('allow_concurrent_appointments', models.BooleanField(default=False)),
                ('max_concurrent_appointments', models.PositiveIntegerField(default=1, help_text='Used only if concurrent appointments are enabled')),
                ('require_approval_for_new_patients', models.BooleanField(default=False)),
                ('auto_confirm_appointments', models.BooleanField(default=True)),
                ('allow_patient_rescheduling', models.BooleanField(default=True)),
                ('reschedule_cutoff_hours', models.PositiveIntegerField(default=6)),
                ('allow_patient_cancellation', models.BooleanField(default=True)),
                ('cancellation_cutoff_hours', models.PositiveIntegerField(default=4)),
                ('advance_booking_days', models.PositiveIntegerField(default=14, help_text='How many days in advance appointments can be booked')),
                ('allow_emergency_slots', models.BooleanField(default=True)),
                ('emergency_slots_per_day', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_scheduling_rules', to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_rules', to='doctor.doctor')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
