# Generated by Django 5.0.7 on 2026-02-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_doctorschedulingrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
