"""Laboratory routing decision audit constants."""

from business_audit.decision.constants import (
    DECISION_STATE_ASSIGNED,
    DECISION_STATE_COMPARED,
    DECISION_STATE_DISCOUNTED,
    DECISION_STATE_FAILED,
    DECISION_STATE_MATCHED,
    DECISION_STATE_RULE_EVALUATED,
    DECISION_STATE_STARTED,
)

DOMAIN_DIAGNOSTICS = "diagnostics_engine"
SERVICE_ROUTING = "RoutingService"
SERVICE_ASSIGNMENT = "AssignmentService"
SERVICE_RECOMMENDATION = "LabRecommendationService"

OPERATION_START_ROUTING = "start_routing_for_order"
OPERATION_EVALUATE_RULES = "evaluate_eligibility_rules"
OPERATION_MATCH_LABS = "match_eligible_labs"
OPERATION_COMPARE_PRICES = "compare_ranked_labs"
OPERATION_APPLY_DISCOUNT = "apply_routing_discount"
OPERATION_ASSIGN_LAB = "assign_routing_winner"
OPERATION_ROUTING_FAILED = "routing_pipeline_failed"
OPERATION_MANUAL_OVERRIDE = "manual_routing_override"

MARKETPLACE_NAME = "DoctorPro Marketplace"

STAGE_STARTED = "started"
STAGE_RULE_EVALUATED = "rule_evaluated"
STAGE_MATCHED = "matched"
STAGE_COMPARED = "compared"
STAGE_DISCOUNTED = "discounted"
STAGE_ASSIGNED = "assigned"
STAGE_FAILED = "failed"
STAGE_MANUAL_OVERRIDE = "manual_override"

DECISION_PATH_SUCCESS = [
    STAGE_RULE_EVALUATED,
    STAGE_MATCHED,
    STAGE_COMPARED,
    STAGE_ASSIGNED,
]

DECISION_PATH_SUCCESS_WITH_DISCOUNT = [
    STAGE_RULE_EVALUATED,
    STAGE_MATCHED,
    STAGE_COMPARED,
    STAGE_DISCOUNTED,
    STAGE_ASSIGNED,
]

DECISION_PATH_FAILED = [STAGE_RULE_EVALUATED, STAGE_MATCHED, STAGE_FAILED]

__all__ = [
    "DECISION_STATE_ASSIGNED",
    "DECISION_STATE_COMPARED",
    "DECISION_STATE_DISCOUNTED",
    "DECISION_STATE_FAILED",
    "DECISION_STATE_MATCHED",
    "DECISION_STATE_RULE_EVALUATED",
    "DECISION_STATE_STARTED",
    "DOMAIN_DIAGNOSTICS",
    "SERVICE_ROUTING",
    "SERVICE_ASSIGNMENT",
    "SERVICE_RECOMMENDATION",
    "OPERATION_START_ROUTING",
    "OPERATION_EVALUATE_RULES",
    "OPERATION_MATCH_LABS",
    "OPERATION_COMPARE_PRICES",
    "OPERATION_APPLY_DISCOUNT",
    "OPERATION_ASSIGN_LAB",
    "OPERATION_ROUTING_FAILED",
    "OPERATION_MANUAL_OVERRIDE",
    "MARKETPLACE_NAME",
    "STAGE_STARTED",
    "STAGE_RULE_EVALUATED",
    "STAGE_MATCHED",
    "STAGE_COMPARED",
    "STAGE_DISCOUNTED",
    "STAGE_ASSIGNED",
    "STAGE_FAILED",
    "STAGE_MANUAL_OVERRIDE",
    "DECISION_PATH_SUCCESS",
    "DECISION_PATH_SUCCESS_WITH_DISCOUNT",
    "DECISION_PATH_FAILED",
]
