# Generated by Django 5.0.7 on 2026-02-22 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_appointmenthistory'),
        ('clinic', '0010_clinic_code'),
        ('doctor', '0031_doctor_public_id'),
        ('patient_account', '0007_patientprofile_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEncounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_pnr', models.CharField(db_index=True, editable=False, help_text='Format: YYMMDD-CL-XXXXX-XXX', max_length=30, unique=True)),
                ('encounter_type', models.CharField(choices=[('appointment', 'Appointment'), ('walk_in', 'Walk In'), ('emergency', 'Emergency'), ('follow_up', 'Follow Up')], default='walk_in', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pre_consultation', 'Pre Consultation'), ('in_consultation', 'In Consultation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='created', max_length=20)),
                ('consultation_type', models.CharField(choices=[('FULL', 'Full Consultation'), ('QUICK_RX', 'Quick Prescription'), ('TEST_ONLY', 'Test Only Visit')], default='FULL', help_text='Workflow type governing visible sections and validation', max_length=20)),
                ('entry_mode', models.CharField(choices=[('helpdesk', 'Helpdesk'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('system', 'System')], default='helpdesk', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='appointments.appointment')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='clinic.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='doctor.doctor')),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patient_account.patientaccount')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='patient_account.patientprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Encounter',
                'verbose_name_plural': 'Clinical Encounters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialty_code', models.CharField(help_text='Specialty code used to resolve templates (e.g. gynecology, physician)', max_length=50)),
                ('template_version', models.CharField(default='v1', help_text='Template version used at time of data entry', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set when pre-consultation is marked complete', null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked once consultation starts')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('lock_reason', models.CharField(blank=True, help_text='Reason for locking (e.g. Consultation started)', max_length=100, null=True)),
                ('entry_mode', models.CharField(choices=[('helpdesk', 'Helpdesk'), ('doctor', 'Doctor'), ('patient', 'Patient'), ('system', 'System')], default='helpdesk', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preconsultations_created', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_consultation', to='consultations_core.clinicalencounter')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preconsultations_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre Consultation',
                'verbose_name_plural': 'Pre Consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreConsultationAllergies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(help_text='Section identifier (e.g. vitals, chief_complaint)', max_length=50)),
                ('schema_version', models.CharField(default='v1', help_text='Schema version of this section', max_length=20)),
                ('data', models.JSONField(help_text='Template-driven JSON data for this section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pre_consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations_core.preconsultation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PreConsultation Allergies',
                'verbose_name_plural': 'PreConsultation Allergies',
            },
        ),
        migrations.CreateModel(
            name='PreConsultationChiefComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(help_text='Section identifier (e.g. vitals, chief_complaint)', max_length=50)),
                ('schema_version', models.CharField(default='v1', help_text='Schema version of this section', max_length=20)),
                ('data', models.JSONField(help_text='Template-driven JSON data for this section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pre_consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations_core.preconsultation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PreConsultation Chief Complaint',
                'verbose_name_plural': 'PreConsultation Chief Complaints',
            },
        ),
        migrations.CreateModel(
            name='PreConsultationMedicalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(help_text='Section identifier (e.g. vitals, chief_complaint)', max_length=50)),
                ('schema_version', models.CharField(default='v1', help_text='Schema version of this section', max_length=20)),
                ('data', models.JSONField(help_text='Template-driven JSON data for this section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pre_consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations_core.preconsultation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PreConsultation Medical History',
                'verbose_name_plural': 'PreConsultation Medical Histories',
            },
        ),
        migrations.CreateModel(
            name='PreConsultationVitals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_code', models.CharField(help_text='Section identifier (e.g. vitals, chief_complaint)', max_length=50)),
                ('schema_version', models.CharField(default='v1', help_text='Schema version of this section', max_length=20)),
                ('data', models.JSONField(help_text='Template-driven JSON data for this section')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('pre_consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultations_core.preconsultation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PreConsultation Vitals',
                'verbose_name_plural': 'PreConsultation Vitals',
            },
        ),
        migrations.CreateModel(
            name='EncounterDailyCounter',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('counter', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_counters', to='clinic.clinic')),
            ],
            options={
                'verbose_name': 'Encounter Daily Counter',
                'verbose_name_plural': 'Encounter Daily Counters',
                'indexes': [models.Index(fields=['clinic', 'date'], name='consultatio_clinic__264914_idx')],
                'unique_together': {('clinic', 'date')},
            },
        ),
    ]
