# Generated by Django 5.0.7 on 2026-02-28 07:57

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0002_add_instruction_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closure_note', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationDiagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis_type', models.CharField(choices=[('provisional', 'Provisional'), ('confirmed', 'Confirmed'), ('differential', 'Differential'), ('chronic_condition', 'Chronic Condition'), ('symptom_based', 'Symptom Based')], db_index=True, default='provisional', max_length=30)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_chronic', models.BooleanField(default=False)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('doctor_note', models.TextField(blank=True, null=True)),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], db_index=True, max_length=20, null=True)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], db_index=True, max_length=20, null=True)),
                ('onset', models.CharField(blank=True, choices=[('sudden', 'Sudden'), ('gradual', 'Gradual')], db_index=True, max_length=20, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('extra_data', models.JSONField(blank=True, help_text='Specialty-specific controlled extension fields', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=150, unique=True)),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('clinical_term', models.CharField(blank=True, max_length=255, null=True)),
                ('icd10_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('is_chronic', models.BooleanField(default=False)),
                ('severity_supported', models.BooleanField(default=False)),
                ('is_primary_allowed', models.BooleanField(default=True)),
                ('synonyms', models.JSONField(blank=True, null=True)),
                ('search_keywords', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EncounterStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyDiagnosisMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialty', models.CharField(db_index=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomExtensionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(help_text='Validated specialty metadata')),
                ('schema_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable internal code (e.g., CHEST_PAIN)', max_length=50, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('specialty', models.CharField(db_index=True, help_text='Mapped specialty', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='instructiontemplateversion',
            name='consultatio_template_version_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='specialtyinstructionmapping',
            name='consultatio_specialty_instruction_uniq',
        ),
        migrations.RemoveIndex(
            model_name='encounterinstruction',
            name='cc_enc_inst_enc_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounterinstruction',
            name='cc_enc_inst_tpl_idx',
        ),
        migrations.RemoveIndex(
            model_name='instructiontemplate',
            name='cc_inst_tpl_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='encounterinstruction',
            new_name='consultatio_is_acti_25d3ba_idx',
            old_name='cc_enc_inst_act_idx',
        ),
        migrations.RenameIndex(
            model_name='instructiontemplate',
            new_name='consultatio_key_3fe5d8_idx',
            old_name='cc_inst_tpl_key_idx',
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consultation is finalized', null=True),
        ),
        migrations.AddField(
            model_name='clinicalencounter',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when doctor starts consultation', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='instructiontemplateversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='specialtyinstructionmapping',
            unique_together={('specialty', 'instruction')},
        ),
        migrations.AddIndex(
            model_name='encounterinstruction',
            index=models.Index(fields=['encounter'], name='consultatio_encount_95a54c_idx'),
        ),
        migrations.AddIndex(
            model_name='encounterinstruction',
            index=models.Index(fields=['instruction_template'], name='consultatio_instruc_c6fe11_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionauditlog',
            index=models.Index(fields=['encounter_instruction'], name='consultatio_encount_21c7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='instructionauditlog',
            index=models.Index(fields=['action'], name='consultatio_action_384488_idx'),
        ),
        migrations.AddIndex(
            model_name='instructioncategory',
            index=models.Index(fields=['code'], name='consultatio_code_d8e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='instructioncategory',
            index=models.Index(fields=['name'], name='consultatio_name_6a66e0_idx'),
        ),
        migrations.AddIndex(
            model_name='instructioncategory',
            index=models.Index(fields=['is_active'], name='consultatio_is_acti_b4f99a_idx'),
        ),
        migrations.AddIndex(
            model_name='instructiontemplate',
            index=models.Index(fields=['category'], name='consultatio_categor_be6ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='instructiontemplateversion',
            index=models.Index(fields=['template'], name='consultatio_templat_93544d_idx'),
        ),
        migrations.AddIndex(
            model_name='instructiontemplateversion',
            index=models.Index(fields=['version_number'], name='consultatio_version_ea1f8c_idx'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='encounter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='consultations_core.clinicalencounter'),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='consultations_core.consultation'),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationsymptom',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='consultations_core.consultation'),
        ),
        migrations.AddField(
            model_name='consultationsymptom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptoms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationsymptom',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptoms_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosismaster',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='consultations_core.diagnosismaster'),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_entries', to='consultations_core.diagnosismaster'),
        ),
        migrations.AddField(
            model_name='encounterstatuslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounterstatuslog',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='consultations_core.clinicalencounter'),
        ),
        migrations.AddField(
            model_name='specialtydiagnosismap',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_mappings', to='consultations_core.diagnosismaster'),
        ),
        migrations.AddField(
            model_name='symptomextensiondata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_extensions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='symptomextensiondata',
            name='symptom_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='consultations_core.consultationsymptom'),
        ),
        migrations.AddField(
            model_name='symptomextensiondata',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_extensions_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='symptommaster',
            index=models.Index(fields=['specialty'], name='consultatio_special_611063_idx'),
        ),
        migrations.AddIndex(
            model_name='symptommaster',
            index=models.Index(fields=['display_name'], name='consultatio_display_838346_idx'),
        ),
        migrations.AddField(
            model_name='consultationsymptom',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_entries', to='consultations_core.symptommaster'),
        ),
        migrations.AddConstraint(
            model_name='consultation',
            constraint=models.CheckConstraint(check=models.Q(('ended_at__isnull', True), ('is_finalized', True), _negated=True), name='finalized_must_have_ended_at'),
        ),
        migrations.AddIndex(
            model_name='diagnosismaster',
            index=models.Index(fields=['key'], name='consultatio_key_562860_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosismaster',
            index=models.Index(fields=['icd10_code'], name='consultatio_icd10_c_408e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosismaster',
            index=models.Index(fields=['category'], name='consultatio_categor_271505_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosismaster',
            index=models.Index(fields=['is_active'], name='consultatio_is_acti_644756_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationdiagnosis',
            index=models.Index(fields=['consultation', 'is_primary'], name='consultatio_consult_f96ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationdiagnosis',
            index=models.Index(fields=['consultation', 'diagnosis_type'], name='consultatio_consult_e88603_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationdiagnosis',
            index=models.Index(fields=['consultation', 'is_active'], name='consultatio_consult_a4688c_idx'),
        ),
        migrations.AddIndex(
            model_name='specialtydiagnosismap',
            index=models.Index(fields=['specialty'], name='consultatio_special_f347cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='specialtydiagnosismap',
            unique_together={('specialty', 'diagnosis')},
        ),
        migrations.AddIndex(
            model_name='symptomextensiondata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['data'], name='consultatio_data_963059_gin'),
        ),
        migrations.AddIndex(
            model_name='consultationsymptom',
            index=models.Index(fields=['consultation'], name='consultatio_consult_b9b29c_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationsymptom',
            index=models.Index(fields=['symptom'], name='consultatio_symptom_8d40d5_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationsymptom',
            index=models.Index(fields=['severity'], name='consultatio_severit_9caef7_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationsymptom',
            index=models.Index(fields=['onset'], name='consultatio_onset_b0cb92_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationsymptom',
            index=models.Index(fields=['is_primary'], name='consultatio_is_prim_d58c63_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationsymptom',
            index=models.Index(fields=['duration_unit'], name='consultatio_duratio_d513a0_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationsymptom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extra_data'], name='consultatio_extra_d_0790fd_gin'),
        ),
        migrations.AddConstraint(
            model_name='consultationsymptom',
            constraint=models.UniqueConstraint(fields=('consultation', 'symptom'), name='unique_symptom_per_consultation'),
        ),
    ]
