# Generated by Django 5.0.7 on 2026-02-28 08:01

from django.conf import settings
from django.db import migrations, models


def deactivate_duplicate_active_encounters(apps, schema_editor):
    """
    For each (patient_account, clinic) with multiple active encounters,
    keep the most recent (by created_at) and set is_active=False on the rest
    so the unique constraint can be applied.
    """
    ClinicalEncounter = apps.get_model("consultations_core", "ClinicalEncounter")
    from django.db.models import Count

    # Find (patient_account_id, clinic_id) pairs that have more than one active encounter
    dupes = (
        ClinicalEncounter.objects.filter(is_active=True)
        .values("patient_account_id", "clinic_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for row in dupes:
        pa_id, clinic_id = row["patient_account_id"], row["clinic_id"]
        # Keep the most recent (by created_at); deactivate all others
        encounter_ids = (
            ClinicalEncounter.objects.filter(
                patient_account_id=pa_id, clinic_id=clinic_id, is_active=True
            )
            .order_by("-created_at")
            .values_list("pk", flat=True)
        )
        to_deactivate = list(encounter_ids)[1:]  # all but the first (most recent)
        if to_deactivate:
            ClinicalEncounter.objects.filter(pk__in=to_deactivate).update(
                is_active=False
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmenthistory'),
        ('clinic', '0010_clinic_code'),
        ('consultations_core', '0003_consultation_consultationdiagnosis_and_more'),
        ('doctor', '0031_doctor_public_id'),
        ('patient_account', '0007_patientprofile_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deactivate_duplicate_active_encounters, noop),
        migrations.AddConstraint(
            model_name='clinicalencounter',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('patient_account', 'clinic'), name='unique_active_encounter_per_patient_clinic'),
        ),
    ]
