# Generated by Django 5.0.7 on 2026-02-28 08:52

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0004_clinicalencounter_unique_active_encounter_per_patient_clinic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('severity_supported', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_masters_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finding_masters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finding Master',
                'verbose_name_plural': 'Finding Master',
                'db_table': 'finding_master',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], db_index=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('extension_data', models.JSONField(blank=True, help_text='Controlled JSON extension for dynamic UI fields', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='consultations_core.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings_updated', to=settings.AUTH_USER_MODEL)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_findings', to='consultations_core.findingmaster')),
            ],
            options={
                'verbose_name': 'Consultation Finding',
                'verbose_name_plural': 'Consultation Findings',
                'db_table': 'consultation_finding',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(db_index=True, help_text='Model name (e.g. ClinicalEncounter, Consultation)', max_length=100)),
                ('object_id', models.UUIDField(db_index=True, help_text='Primary key of the object')),
                ('field_name', models.CharField(db_index=True, help_text='Field that changed (e.g. status, is_finalized)', max_length=100)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('system', 'System'), ('doctor', 'Doctor'), ('helpdesk', 'Helpdesk'), ('patient', 'Patient'), ('admin', 'Admin')], default='system', max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for status change', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clinical Audit Log',
                'verbose_name_plural': 'Clinical Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='consultatio_object__eda260_idx'), models.Index(fields=['field_name'], name='consultatio_field_n_076b22_idx'), models.Index(fields=['created_at'], name='consultatio_created_031b54_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='findingmaster',
            index=models.Index(fields=['category'], name='finding_mas_categor_12608e_idx'),
        ),
        migrations.AddIndex(
            model_name='findingmaster',
            index=models.Index(fields=['is_active'], name='finding_mas_is_acti_1a71a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='findingmaster',
            constraint=models.UniqueConstraint(fields=('code',), name='unique_finding_master_code'),
        ),
        migrations.AddIndex(
            model_name='consultationfinding',
            index=models.Index(fields=['consultation'], name='consultatio_consult_56df84_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationfinding',
            index=models.Index(fields=['finding'], name='consultatio_finding_43eac0_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationfinding',
            index=models.Index(fields=['severity'], name='consultatio_severit_3a1202_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationfinding',
            index=models.Index(fields=['is_active'], name='consultatio_is_acti_a1ec12_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationfinding',
            index=models.Index(fields=['created_at'], name='consultatio_created_fffc57_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationfinding',
            index=models.Index(fields=['finding', 'severity'], name='consultatio_finding_38caa3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationfinding',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extension_data'], name='consultatio_extensi_72b6a5_gin'),
        ),
        migrations.AddConstraint(
            model_name='consultationfinding',
            constraint=models.UniqueConstraint(fields=('consultation', 'finding'), name='unique_finding_per_consultation'),
        ),
    ]
