# Generated by Django 5.0.7 on 2026-03-19 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0008_encounter_cancelled_at_cancelled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationsymptom',
            name='display_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='consultationsymptom',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clinicalencounter',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when consultation is finalized (use consultation_end_time)', null=True),
        ),
        migrations.AlterField(
            model_name='clinicalencounter',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when doctor starts consultation (use consultation_start_time)', null=True),
        ),
        migrations.AlterField(
            model_name='consultationsymptom',
            name='symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultation_entries', to='consultations_core.symptommaster'),
        ),
        migrations.AlterField(
            model_name='symptommaster',
            name='display_name',
            field=models.CharField(db_index=True, default='Unknown', max_length=255),
        ),
        migrations.CreateModel(
            name='CustomSymptom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_symptoms', to='consultations_core.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consultationsymptom',
            name='custom_symptom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_entries', to='consultations_core.customsymptom'),
        ),
        migrations.AddIndex(
            model_name='customsymptom',
            index=models.Index(fields=['name'], name='consultatio_name_c2c1fc_idx'),
        ),
    ]
