# Generated by Django 5.0.7 on 2026-04-03 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0012_consultationdiagnosis_display_name_and_more'),
        ('medicines', '0003_drugcomposition_drugmaster_drug_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('prescription_pnr', models.CharField(db_index=True, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='prescriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations_core.consultation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField(blank=True, null=True)),
                ('diet', models.TextField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='consultations_core.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name_snapshot', models.CharField(max_length=255)),
                ('generic_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('strength_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('formulation_snapshot', models.CharField(max_length=100)),
                ('dose_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=20, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_prn', models.BooleanField(default=False)),
                ('is_stat', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dose_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.doseunitmaster')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.drugmaster')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.frequencymaster')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='consultations_core.prescription')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicines.routemaster')),
            ],
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['consultation'], name='consultatio_consult_882806_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='consultatio_status_6efa1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('consultation',), name='unique_active_prescription_per_consultation'),
        ),
        migrations.AddIndex(
            model_name='prescriptionline',
            index=models.Index(fields=['prescription'], name='consultatio_prescri_9ac9e2_idx'),
        ),
    ]
