# Generated by Django 5.0.7 on 2026-04-03 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0013_prescription_prescriptioninstruction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.UniqueConstraint(fields=('consultation', 'version_number'), name='unique_rx_version_per_consultation'),
        ),
    ]
