# Generated by Django 5.0.7 on 2026-04-04 18:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_clinic_code'),
        ('consultations_core', '0014_prescription_unique_rx_version_per_consultation'),
        ('medicines', '0005_drugcomposition_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptioninstruction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptioninstruction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptioninstruction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptioninstruction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # PrescriptionInstruction originally used BigAutoField (0013). PostgreSQL cannot
        # ALTER COLUMN bigint TO uuid USING id::uuid — replace PK via a new column instead.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE consultations_core_prescriptioninstruction
                        ADD COLUMN id_uuid uuid;
                    UPDATE consultations_core_prescriptioninstruction
                        SET id_uuid = gen_random_uuid();
                    ALTER TABLE consultations_core_prescriptioninstruction
                        DROP CONSTRAINT consultations_core_prescriptioninstruction_pkey;
                    ALTER TABLE consultations_core_prescriptioninstruction
                        DROP COLUMN id;
                    ALTER TABLE consultations_core_prescriptioninstruction
                        RENAME COLUMN id_uuid TO id;
                    ALTER TABLE consultations_core_prescriptioninstruction
                        ALTER COLUMN id SET NOT NULL;
                    ALTER TABLE consultations_core_prescriptioninstruction
                        ADD CONSTRAINT consultations_core_prescriptioninstruction_pkey
                        PRIMARY KEY (id);
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='prescriptioninstruction',
                    name='id',
                    field=models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='prescriptionline',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicines.drugmaster'),
        ),
        migrations.CreateModel(
            name='CustomMedicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dose_type', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('powder', 'Powder'), ('other', 'Other')], db_index=True, max_length=50)),
                ('strength_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('strength_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_normalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_medicines_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_medicines_deleted', to=settings.AUTH_USER_MODEL)),
                ('normalized_drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.drugmaster')),
            ],
        ),
        migrations.AddField(
            model_name='prescriptionline',
            name='custom_medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='consultations_core.custommedicine'),
        ),
        migrations.AddIndex(
            model_name='custommedicine',
            index=models.Index(fields=['name'], name='consultatio_name_f6b0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='custommedicine',
            index=models.Index(fields=['clinic'], name='consultatio_clinic__8b9dcb_idx'),
        ),
    ]
