# Generated by Django 5.0.7 on 2026-04-08 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0016_diagnosismaster_soft_delete_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationdiagnosis',
            name='source',
            field=models.CharField(choices=[('emr', 'From EMR'), ('app', 'From Patient App'), ('admin', 'Manual/Admin'), ('api', 'External API')], db_index=True, default='emr', max_length=20),
        ),
        migrations.AddField(
            model_name='customdiagnosis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customdiagnosis',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_diagnoses_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customdiagnosis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='specialtydiagnosismap',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialtydiagnosismap',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_diagnosis_maps_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='customdiagnosis',
            unique_together={('consultation', 'name')},
        ),
        migrations.AddIndex(
            model_name='consultationdiagnosis',
            index=models.Index(fields=['source'], name='consultatio_source_b613da_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationdiagnosis',
            index=models.Index(fields=['consultation', 'is_active', 'is_primary'], name='consultatio_consult_b14055_idx'),
        ),
        migrations.AddIndex(
            model_name='customdiagnosis',
            index=models.Index(fields=['consultation'], name='consultatio_consult_3885a3_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosismaster',
            index=models.Index(fields=['parent'], name='consultatio_parent__cf9776_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosismaster',
            index=models.Index(fields=['label'], name='consultatio_label_238303_idx'),
        ),
        migrations.AddIndex(
            model_name='specialtydiagnosismap',
            index=models.Index(fields=['diagnosis'], name='consultatio_diagnos_26be4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultationdiagnosis',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('consultation',), name='unique_active_primary_diagnosis_per_consultation'),
        ),
    ]
