# Generated by Django 5.0.7 on 2026-04-09 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_clinic_code'),
        ('consultations_core', '0017_consultationdiagnosis_deleted_at_and_more'),
        ('diagnostics_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationInvestigations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='consultations_core.consultation')),
            ],
            options={
                'db_table': 'consultation_investigations',
            },
        ),
        migrations.CreateModel(
            name='CustomInvestigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('investigation_type', models.CharField(choices=[('lab', 'Lab Test'), ('radiology', 'Radiology'), ('scan', 'Scan'), ('package', 'Package'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_investigations', to='clinic.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_investigations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_investigations',
            },
        ),
        migrations.CreateModel(
            name='InvestigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('catalog', 'Catalog'), ('custom', 'Custom')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('investigation_type', models.CharField(choices=[('lab', 'Lab Test'), ('radiology', 'Radiology'), ('scan', 'Scan'), ('package', 'Package'), ('other', 'Other')], default='lab', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('ordered', 'Ordered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='suggested', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(db_index=True, default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_investigation_items', to='diagnostics_engine.diagnosticservicemaster')),
                ('custom_investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_items', to='consultations_core.custominvestigation')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_items_deleted', to=settings.AUTH_USER_MODEL)),
                ('diagnostic_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_investigation_items', to='diagnostics_engine.diagnosticorderitem')),
                ('investigations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations_core.consultationinvestigations')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_items_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consultation_investigation_items',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='custominvestigation',
            index=models.Index(fields=['name'], name='custom_inve_name_43d07d_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationitem',
            index=models.Index(fields=['investigations'], name='consultatio_investi_838cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationitem',
            index=models.Index(fields=['status'], name='consultatio_status_517038_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationitem',
            index=models.Index(fields=['diagnostic_order_item'], name='consultatio_diagnos_c85a87_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationitem',
            index=models.Index(fields=['investigations', 'is_deleted', 'position'], name='consultatio_investi_c08c14_idx'),
        ),
        migrations.AddConstraint(
            model_name='investigationitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('catalog_item__isnull', False), ('custom_investigation__isnull', True), ('source', 'catalog')), models.Q(('catalog_item__isnull', True), ('source', 'custom')), _connector='OR'), name='investigation_item_source_mapping_valid'),
        ),
        migrations.AddConstraint(
            model_name='investigationitem',
            constraint=models.CheckConstraint(check=models.Q(('custom_investigation__isnull', True), ('name', ''), ('source', 'custom'), _negated=True), name='investigation_item_custom_requires_name_or_custom'),
        ),
        migrations.AddConstraint(
            model_name='investigationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('investigations', 'position'), name='uniq_active_investigation_position_per_consultation'),
        ),
    ]
