# Generated by Django 5.0.7 on 2026-04-10 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0018_consultationinvestigations_custominvestigation_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='investigationitem',
            name='investigation_item_source_mapping_valid',
        ),
    ]
