# Generated by Django 5.0.7 on 2026-04-10 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0019_diagnostic_packages'),
        ('diagnostics_engine', '0002_diagnostic_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigationitem',
            name='diagnostic_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_investigation_items', to='diagnostics_engine.diagnosticpackage'),
        ),
        migrations.AddField(
            model_name='investigationitem',
            name='package_expansion_snapshot',
            field=models.JSONField(blank=True, help_text='Per-service lines when doctor edits package contents (service_id, included, instructions, urgency).', null=True),
        ),
        migrations.AddField(
            model_name='investigationitem',
            name='prescription_source',
            field=models.CharField(choices=[('doctor_selected', 'Doctor selected'), ('template', 'Template'), ('ai', 'AI')], default='doctor_selected', max_length=30),
        ),
        migrations.AlterField(
            model_name='investigationitem',
            name='source',
            field=models.CharField(choices=[('catalog', 'Catalog'), ('custom', 'Custom'), ('package', 'Package')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='investigationitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('catalog_item__isnull', False), ('custom_investigation__isnull', True), ('diagnostic_package__isnull', True), ('source', 'catalog')), models.Q(('catalog_item__isnull', True), ('diagnostic_package__isnull', True), ('source', 'custom')), models.Q(('catalog_item__isnull', True), ('custom_investigation__isnull', True), ('diagnostic_package__isnull', False), ('source', 'package')), _connector='OR'), name='investigation_item_source_mapping_valid'),
        ),
    ]
