# Generated by Django 5.0.7 on 2026-04-12 16:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0020_diagnostic_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDoctorInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('normalized_text', models.CharField(db_index=True, max_length=255)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='encounterinstruction',
            name='unique_active_instruction_per_encounter',
        ),
        migrations.AddField(
            model_name='encounterinstruction',
            name='is_custom',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='encounterinstruction',
            name='source',
            field=models.CharField(choices=[('template', 'Template'), ('doctor', 'Doctor'), ('custom', 'Custom')], db_index=True, default='template', max_length=20),
        ),
        migrations.AddField(
            model_name='encounterinstruction',
            name='text_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='encounterinstruction',
            name='instruction_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='consultations_core.instructiontemplate'),
        ),
        migrations.AlterField(
            model_name='encounterinstruction',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='consultations_core.instructiontemplateversion'),
        ),
        migrations.AddConstraint(
            model_name='encounterinstruction',
            constraint=models.UniqueConstraint(fields=('encounter', 'instruction_template', 'template_version', 'is_active'), name='unique_active_instruction_per_encounter_v2'),
        ),
        migrations.AddField(
            model_name='customdoctorinstruction',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_instructions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customdoctorinstruction',
            index=models.Index(fields=['doctor', 'normalized_text'], name='consultatio_doctor__6fdb14_idx'),
        ),
        migrations.AddIndex(
            model_name='customdoctorinstruction',
            index=models.Index(fields=['is_active'], name='consultatio_is_acti_83da59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customdoctorinstruction',
            unique_together={('doctor', 'normalized_text')},
        ),
    ]
