# Generated by Django 5.0.7 on 2026-04-14 04:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0021_encounter_instruction_snapshot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_up_type', models.CharField(choices=[('exact_date', 'Exact Date'), ('after_days', 'After X Days'), ('after_weeks', 'After X Weeks'), ('conditional', 'Conditional'), ('after_test', 'After Test'), ('asap', 'As Soon As Possible')], max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('after_value', models.PositiveIntegerField(blank=True, null=True)),
                ('condition_note', models.TextField(blank=True, null=True)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='consultations_core.consultation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.UniqueConstraint(fields=('consultation',), name='unique_follow_up_per_consultation'),
        ),
    ]
