# Generated by Django 5.0.7 on 2026-04-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0024_clinical_template'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clinicaltemplate',
            new_name='clinical_te_doctor__f25c8d_idx',
            old_name='clinical_temp_doctor_id_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicaltemplate',
            new_name='clinical_te_consult_8a5f65_idx',
            old_name='clinical_temp_consult_typ_idx',
        ),
    ]
