# Generated by Django 5.0.7 on 2025-01-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('hospital_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontdeskuser',
            name='hospital',
        ),
        migrations.AddField(
            model_name='frontdeskuser',
            name='clinic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_users', to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='frontdeskuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
