# Generated by Django 5.0.7 on 2024-12-29 18:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='emergency_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(default=datetime.datetime(2024, 12, 29, 18, 49, 11, 843688, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='owner_contact',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='owner_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='registration_number',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HospitalBillingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_practices', models.TextField(blank=True, null=True)),
                ('discount_policies', models.TextField(blank=True, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_information', to='hospital_mgmt.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalDigitalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_management_software', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_appointment_channels', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_data_management', models.TextField(blank=True, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_information', to='hospital_mgmt.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_facilities', models.TextField(blank=True, null=True)),
                ('medical_equipment', models.TextField(blank=True, null=True)),
                ('ambulance_services', models.TextField(blank=True, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='hospital_mgmt.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalLicensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_license_details', models.CharField(max_length=255)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('tax_information', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licensing', to='hospital_mgmt.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalOperationalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_beds', models.IntegerField(blank=True, null=True)),
                ('departments_services_offered', models.TextField(blank=True, null=True)),
                ('hospital_timings', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_partnerships', models.TextField(blank=True, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operational_details', to='hospital_mgmt.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors', models.IntegerField(blank=True, null=True)),
                ('nurses_and_technicians', models.IntegerField(blank=True, null=True)),
                ('administrative_staff', models.IntegerField(blank=True, null=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_details', to='hospital_mgmt.hospital')),
            ],
        ),
    ]
