from .appointment import (
    AppointmentCancelView,
    AppointmentCheckInView,
    AppointmentCreateView,
    AppointmentListView,
    AppointmentDetailView,
    AppointmentHistoryView,
    AppointmentRescheduleView,
    AppointmentSlotView,
    AppointmentStatusUpdateView,
    AppointmentTodayMetricsView,
    DoctorAppointmentsView,
    DoctorCalendarView,
    PatientAppointmentsView,
    WalkInAppointmentCreateView,
)

__all__ = [
    "AppointmentListView",
    "AppointmentCreateView",
    "AppointmentDetailView",
    "AppointmentCancelView",
    "AppointmentCheckInView",
    "AppointmentRescheduleView",
    "PatientAppointmentsView",
    "DoctorAppointmentsView",
    "AppointmentSlotView",
    "AppointmentHistoryView",
    "AppointmentStatusUpdateView",
    "WalkInAppointmentCreateView",
    "AppointmentTodayMetricsView",
    "DoctorCalendarView",
]
