# Generated by Django 5.0.7 on 2026-06-27 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

INDEX_RENAMES = (
    ("whatsapp_me_status_8e2f0a_idx", "whatsapp_me_status_9013c7_idx"),
    ("whatsapp_me_patient_2c8b91_idx", "whatsapp_me_patient_d20792_idx"),
    ("whatsapp_me_clinic_91ad44_idx", "whatsapp_me_clinic__7faf6e_idx"),
    ("whatsapp_me_meta_me_0f3de2_idx", "whatsapp_me_meta_me_d96a4f_idx"),
    ("whatsapp_me_recipie_7b1c22_idx", "whatsapp_me_recipie_656cf1_idx"),
    ("whatsapp_me_provide_4a8c10_idx", "whatsapp_me_provide_6e117b_idx"),
    ("whatsapp_me_convers_6d2e88_idx", "whatsapp_me_convers_dadd77_idx"),
    ("whatsapp_me_idempot_3f1a90_idx", "whatsapp_me_idempot_cbad98_idx"),
)


def _rename_indexes(apps, schema_editor, renames):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        for old_name, new_name in renames:
            cursor.execute(
                "SELECT 1 FROM pg_indexes WHERE indexname = %s",
                [old_name],
            )
            if cursor.fetchone():
                cursor.execute(
                    f'ALTER INDEX "{old_name}" RENAME TO "{new_name}"',
                )


def rename_indexes_forward(apps, schema_editor):
    _rename_indexes(apps, schema_editor, INDEX_RENAMES)


def rename_indexes_backward(apps, schema_editor):
    _rename_indexes(
        apps,
        schema_editor,
        [(new, old) for old, new in INDEX_RENAMES],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_remove_appointment_appt_clinic_stat_date_slot_idx_and_more'),
        ('clinic', '0010_clinic_code'),
        ('consultations_core', '0027_clinicaltemplate_usage_count'),
        ('diagnostics_engine', '0016_rename_diagnostics_patient_pr_8f0901_idx_diagnostics_patient_e80b58_idx_and_more'),
        ('doctor', '0031_doctor_public_id'),
        ('notifications', '0002_whatsappmessage_deleted_by'),
        ('patient_account', '0010_patient_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_status_9013c7_idx",
                    old_name="whatsapp_me_status_8e2f0a_idx",
                ),
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_patient_d20792_idx",
                    old_name="whatsapp_me_patient_2c8b91_idx",
                ),
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_clinic__7faf6e_idx",
                    old_name="whatsapp_me_clinic_91ad44_idx",
                ),
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_meta_me_d96a4f_idx",
                    old_name="whatsapp_me_meta_me_0f3de2_idx",
                ),
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_recipie_656cf1_idx",
                    old_name="whatsapp_me_recipie_7b1c22_idx",
                ),
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_provide_6e117b_idx",
                    old_name="whatsapp_me_provide_4a8c10_idx",
                ),
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_convers_dadd77_idx",
                    old_name="whatsapp_me_convers_6d2e88_idx",
                ),
                migrations.RenameIndex(
                    model_name="whatsappmessage",
                    new_name="whatsapp_me_idempot_cbad98_idx",
                    old_name="whatsapp_me_idempot_3f1a90_idx",
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    rename_indexes_forward,
                    rename_indexes_backward,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Appointment linked to this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Clinic context for the outbound message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='clinic.clinic'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the message was delivered to the device.', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='diagnostic_order',
            field=models.ForeignKey(blank=True, help_text='Diagnostic order linked to test-booking messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='diagnostics_engine.diagnosticorder'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='diagnostic_test_report',
            field=models.ForeignKey(blank=True, help_text='Diagnostic test report linked to this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='diagnostics_engine.diagnostictestreport'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor context for appointment or prescription messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='encounter',
            field=models.ForeignKey(blank=True, help_text='Clinical encounter linked to this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='consultations_core.clinicalencounter'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='error_code',
            field=models.CharField(blank=True, help_text='Provider or platform error code when delivery fails.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Human-readable failure reason from the provider or platform.', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last retry attempt.', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='patient',
            field=models.ForeignKey(blank=True, help_text='Patient profile the message relates to, when applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='patient_account.patientprofile'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Prescription linked to this message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='consultations_core.prescription'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='queued_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the message was queued for send.', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the recipient read the message.', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Outgoing payload sent to the WhatsApp provider.'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Provider response received immediately after send.'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of delivery retry attempts.'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the provider accepted the send.', null=True),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='webhook_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Latest webhook payload received from provider.'),
        ),
    ]
