"""Generic communication audit FSM state labels."""

COMM_STATE_READY = "Ready"
COMM_STATE_QUEUED = "Queued"
COMM_STATE_SENDING = "Sending"
COMM_STATE_SENT = "Sent"
COMM_STATE_DELIVERED = "Delivered"
COMM_STATE_READ = "Read"
COMM_STATE_ACKNOWLEDGED = "Acknowledged"
COMM_STATE_FAILED = "Failed"
COMM_STATE_RETRY = "Retry"
COMM_STATE_EXPIRED = "Expired"
COMM_STATE_CANCELLED = "Cancelled"
COMM_STATE_PUBLISHED = "Published"
COMM_STATE_VIEWED = "Viewed"

ARTIFACT_TYPE_LAB_REPORT_PDF = "LAB_REPORT_PDF"
DEFAULT_MIME_PDF = "application/pdf"

AVAILABLE_CHANNELS_DEFAULT = ["WHATSAPP", "EMAIL", "SMS", "PORTAL"]
FALLBACK_ORDER_DEFAULT = ["EMAIL", "SMS", "PORTAL"]
