# Generated by Django 5.0.7 on 2026-04-10 04:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0019_diagnostic_packages'),
        ('diagnostics_engine', '0001_initial'),
        ('doctor', '0031_doctor_public_id'),
        ('patient_account', '0007_patientprofile_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPackagePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_margin_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], default='flat', max_length=10)),
                ('platform_margin_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('doctor_commission_type', models.CharField(choices=[('flat', 'Flat Amount'), ('percent', 'Percentage')], default='flat', max_length=10)),
                ('doctor_commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lab_payout_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_source', models.CharField(choices=[('default', 'Default'), ('campaign', 'Campaign'), ('custom', 'Custom')], default='default', max_length=20)),
                ('settlement_cycle', models.CharField(blank=True, max_length=50, null=True)),
                ('fulfillment_mode', models.CharField(choices=[('strict', 'Strict'), ('partial', 'Partial')], default='strict', max_length=20)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticOrderTestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('execution_type', models.CharField(choices=[('home_collection', 'Home Collection'), ('branch_visit', 'Branch Visit'), ('third_party', 'Third Party')], default='branch_visit', max_length=30)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lineage_code', models.CharField(db_index=True, help_text='Stable id across versions (e.g. HEALTH-PLUS).', max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_promoted', models.BooleanField(default=False)),
                ('priority_score', models.PositiveIntegerField(default=0)),
                ('package_type', models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], default='system', max_length=20)),
                ('collection_type', models.CharField(choices=[('home', 'Home'), ('lab', 'Lab'), ('both', 'Both')], default='lab', max_length=10)),
                ('min_tat_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('max_tat_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('fasting_required', models.BooleanField(default=False)),
                ('gender_applicability', models.CharField(choices=[('all', 'All'), ('male', 'Male'), ('female', 'Female')], default='all', max_length=20)),
                ('age_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('conditions_supported', models.JSONField(blank=True, null=True)),
                ('package_popularity_score', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['lineage_code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticPackageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_order', 'service__name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTestReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_mode', models.CharField(choices=[('structured', 'Structured Only'), ('file', 'File Only'), ('hybrid', 'Structured + File')], default='structured', max_length=20)),
                ('structured_result', models.JSONField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='diagnostic_test_reports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_editable', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosticorderitem',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='diagnosticorderitem',
            name='bundle_snapshot',
        ),
        migrations.AddField(
            model_name='branchservicepricing',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Temporarily hide SKU without deleting pricing history.'),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_orders', to='consultations_core.consultation'),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='diagnosticorder',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='composition_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_order_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='is_price_derived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='line_type',
            field=models.CharField(choices=[('test', 'Test'), ('package', 'Package')], default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='package_version_snapshot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_order_items_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnosticorder',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('sample_collected', 'Sample Collected'), ('in_processing', 'In Processing'), ('report_ready', 'Report Ready'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('cancelled', 'Cancelled')], default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='diagnosticorderitem',
            name='recommendation_source',
            field=models.CharField(choices=[('manual', 'Doctor Manual'), ('diagnosis_map', 'Diagnosis Suggested'), ('bundle', 'Bundle Suggested'), ('package', 'Package Suggested'), ('ai', 'AI Suggested')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='diagnosticorderitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diagnostics_engine.diagnosticservicemaster'),
        ),
        migrations.AlterField(
            model_name='diagnosticreport',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='diagnostics_engine.diagnosticorder'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorder',
            index=models.Index(fields=['consultation'], name='diagnostics_consult_89dd93_idx'),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_pricing', to='diagnostics_engine.diagnosticproviderbranch'),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_branch_package_pricing_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_branch_package_pricing_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_branch_package_pricing_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticordertestline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_order_test_lines_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticordertestline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_lines', to='diagnostics_engine.diagnosticorder'),
        ),
        migrations.AddField(
            model_name='diagnosticordertestline',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_lines', to='diagnostics_engine.diagnosticorderitem'),
        ),
        migrations.AddField(
            model_name='diagnosticordertestline',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_test_lines', to='diagnostics_engine.diagnosticservicemaster'),
        ),
        migrations.AddField(
            model_name='diagnosticordertestline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_order_test_lines_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticpackage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='diagnostics_engine.diagnosticcategory'),
        ),
        migrations.AddField(
            model_name='diagnosticpackage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_packages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticpackage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_packages_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticpackage',
            name='parent_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='diagnostics_engine.diagnosticpackage'),
        ),
        migrations.AddField(
            model_name='diagnosticpackage',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_packages_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branchpackagepricing',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_pricing', to='diagnostics_engine.diagnosticpackage'),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='diagnostic_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='diagnostics_engine.diagnosticpackage'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorderitem',
            index=models.Index(fields=['order'], name='diagnostics_order_i_9c5a12_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorderitem',
            index=models.Index(fields=['line_type'], name='diagnostics_line_ty_f70443_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorderitem',
            index=models.Index(fields=['diagnostic_package'], name='diagnostics_diagnos_810be4_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticorderitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('diagnostic_package__isnull', True), ('line_type', 'test'), ('service__isnull', False)), models.Q(('diagnostic_package__isnull', False), ('line_type', 'package'), ('service__isnull', True)), _connector='OR'), name='order_item_line_type_fk_valid'),
        ),
        migrations.AddField(
            model_name='diagnosticpackageitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_package_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticpackageitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_package_items_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosticpackageitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diagnostics_engine.diagnosticpackage'),
        ),
        migrations.AddField(
            model_name='diagnosticpackageitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='diagnostics_engine.diagnosticservicemaster'),
        ),
        migrations.AddField(
            model_name='diagnosticpackageitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_package_items_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_test_reports_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_test_reports_delivered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='order_test_line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_report', to='diagnostics_engine.diagnosticordertestline'),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_test_reports_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DiagnosticBundle',
        ),
        migrations.AddIndex(
            model_name='diagnosticordertestline',
            index=models.Index(fields=['order'], name='diagnostics_order_i_271df2_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticordertestline',
            index=models.Index(fields=['order_item'], name='diagnostics_order_i_286d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticordertestline',
            index=models.Index(fields=['service'], name='diagnostics_service_9dd8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticordertestline',
            index=models.Index(fields=['status'], name='diagnostics_status_de5625_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticpackage',
            index=models.Index(fields=['lineage_code'], name='diagnostics_lineage_84362a_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticpackage',
            index=models.Index(fields=['is_active', 'is_latest'], name='diagnostics_is_acti_7f4bdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticpackage',
            constraint=models.UniqueConstraint(fields=('lineage_code', 'version'), name='uniq_diagnostic_package_lineage_version'),
        ),
        migrations.AddIndex(
            model_name='branchpackagepricing',
            index=models.Index(fields=['branch'], name='diagnostics_branch__63953c_idx'),
        ),
        migrations.AddIndex(
            model_name='branchpackagepricing',
            index=models.Index(fields=['package'], name='diagnostics_package_8ba649_idx'),
        ),
        migrations.AddConstraint(
            model_name='branchpackagepricing',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('branch', 'package'), name='unique_active_branch_package_pricing'),
        ),
        migrations.AddIndex(
            model_name='diagnosticpackageitem',
            index=models.Index(fields=['package'], name='diagnostics_package_090dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticpackageitem',
            index=models.Index(fields=['service'], name='diagnostics_service_7744da_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticpackageitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('package', 'service'), name='uniq_active_package_service'),
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(fields=['status'], name='diagnostics_status_5cc921_idx'),
        ),
    ]
