# Generated by Django 5.0.7 on 2026-04-10 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0020_diagnostic_packages'),
        ('diagnostics_engine', '0002_diagnostic_packages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomTestMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('optional', 'Optional')], db_index=True, default='recommended', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('reason_template', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_test_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_mappings', to='diagnostics_engine.diagnosticservicemaster')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mappings', to='consultations_core.symptommaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_test_mappings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering', '-weight'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisTestMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('optional', 'Optional')], db_index=True, default='recommended', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('reason_template', models.CharField(blank=True, max_length=255, null=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_test_mappings_created', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_mappings', to='consultations_core.diagnosismaster')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_mappings', to='diagnostics_engine.diagnosticservicemaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_test_mappings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ordering', '-weight'],
                'indexes': [models.Index(fields=['diagnosis', 'is_active'], name='diagnostics_diagnos_263f61_idx'), models.Index(fields=['service', 'is_active'], name='diagnostics_service_e5bd5c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='diagnosistestmapping',
            constraint=models.UniqueConstraint(fields=('diagnosis', 'service'), name='uniq_diagnosis_service_mapping'),
        ),
        migrations.AddIndex(
            model_name='symptomtestmapping',
            index=models.Index(fields=['symptom', 'is_active'], name='diagnostics_symptom_6c2c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='symptomtestmapping',
            index=models.Index(fields=['service', 'is_active'], name='diagnostics_service_d19a7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='symptomtestmapping',
            constraint=models.UniqueConstraint(fields=('symptom', 'service'), name='uniq_symptom_service_mapping'),
        ),
    ]
