# Generated by Django 5.0.7 on 2026-04-10 20:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0004_catalog_search_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticservicemaster',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Search tags for catalog search (Postgres ArrayField).', size=None),
        ),
    ]
