# Generated by Django — nullable branch for pre-routing diagnostic orders

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics_engine", "0006_remove_branchservicearea_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticorder",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="diagnostic_orders",
                to="labs.labbranch",
            ),
        ),
    ]
