# Generated by Django 5.0.7 on 2026-05-11 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations_core', '0026_prescription_cancellation_audit_fields'),
        ('diagnostics_engine', '0007_diagnosticorder_branch_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='is_home_collection_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='metadata_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='requires_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='requires_fasting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticorderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('partial', 'Partial'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='diagnosticorderitem',
            index=models.Index(fields=['order', 'status'], name='diagnostics_order_i_10de7f_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorderitem',
            index=models.Index(fields=['service', 'status'], name='diagnostics_service_073411_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorderitem',
            index=models.Index(fields=['diagnosis'], name='diagnostics_diagnos_12b379_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticorderitem',
            index=models.Index(fields=['is_active'], name='diagnostics_is_acti_90bed3_idx'),
        ),
    ]
