# Generated by Django 5.0.7 on 2026-05-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0010_diagnosticorder_routing_status_and_routing_version'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diagnosticorder',
            new_name='diagnostics_routing_c84008_idx',
            old_name='diagnostics_routing_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='routingrun',
            new_name='diagnostics_routing_4f32fd_idx',
            old_name='diagnostics_routing_engine_ver_idx',
        ),
    ]
