# Generated by Django 5.0.7 on 2026-05-18 19:12

import diagnostics_engine.models.reports
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0011_rename_diagnostics_routing_order_status_idx_diagnostics_routing_c84008_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReportArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stored_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('download_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(max_length=512, upload_to=diagnostics_engine.models.reports.build_report_artifact_upload_path)),
                ('artifact_type', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Image'), ('CSV', 'CSV'), ('XLSX', 'Excel'), ('TXT', 'Text'), ('ZIP', 'ZIP'), ('DICOM', 'DICOM')], default='PDF', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_path', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnostictestreport',
            name='file',
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='delivery_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('SENT', 'Sent'),
                    ('DELIVERED', 'Delivered'),
                    ('VIEWED', 'Viewed'),
                    ('FAILED', 'Failed'),
                ],
                default='PENDING',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='report_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_test_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='revision_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='source_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostictestreport',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_reports', to='diagnostics_engine.diagnostictestreport'),
        ),
        migrations.AlterField(
            model_name='diagnostictestreport',
            name='order_test_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_reports', to='diagnostics_engine.diagnosticordertestline'),
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(fields=['delivery_status'], name='diagnostics_deliver_9a61e0_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(fields=['uploaded_at'], name='diagnostics_uploade_be413e_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(fields=['order_test_line'], name='diagnostics_order_t_e85731_idx'),
        ),
        migrations.AddField(
            model_name='diagnosticreportartifact',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='diagnostics_engine.diagnostictestreport'),
        ),
        migrations.AddField(
            model_name='diagnosticreportartifact',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_report_artifacts_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='diagnosticreportartifact',
            index=models.Index(fields=['report'], name='diagnostics_report__e39349_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreportartifact',
            index=models.Index(fields=['artifact_type'], name='diagnostics_artifac_489172_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreportartifact',
            index=models.Index(fields=['uploaded_at'], name='diagnostics_uploade_757790_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreportartifact',
            index=models.Index(fields=['is_primary'], name='diagnostics_is_prim_3790a9_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreportartifact',
            index=models.Index(fields=['version'], name='diagnostics_version_fe9af9_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticreportartifact',
            index=models.Index(fields=['is_active'], name='diagnostics_is_acti_823abd_idx'),
        ),
    ]
