# Generated by Django 5.0.7 on 2026-06-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0015_report_reupload_reason'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='diagnosticreportartifact',
            new_name='diagnostics_patient_e80b58_idx',
            old_name='diagnostics_patient_pr_8f0901_idx',
        ),
        migrations.RenameIndex(
            model_name='diagnosticreportartifact',
            new_name='diagnostics_patient_7b9b0e_idx',
            old_name='diagnostics_patient_ac_63c24f_idx',
        ),
        migrations.RenameIndex(
            model_name='diagnosticreportartifact',
            new_name='diagnostics_report__092153_idx',
            old_name='diagnostics_report_c6adfa_idx',
        ),
        migrations.RenameIndex(
            model_name='diagnosticreportartifact',
            new_name='diagnostics_checksu_886028_idx',
            old_name='diagnostics_checksum_9f65e2_idx',
        ),
    ]
