# Generated by Django 5.0.7 on 2026-06-28 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0016_rename_diagnostics_patient_pr_8f0901_idx_diagnostics_patient_e80b58_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceRecommendationApiAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, null=True)),
                ('recommendation_id', models.UUIDField(db_index=True)),
                ('request_id', models.CharField(db_index=True, max_length=128)),
                ('client_request_id', models.CharField(blank=True, default='', max_length=128)),
                ('consultation_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_role_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('query_count', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostics_marketplace_recommendation_api_audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='diagnostics_created_f3ee42_idx'), models.Index(fields=['consultation_id', 'created_at'], name='diagnostics_consult_98e48a_idx')],
            },
        ),
    ]
