# Generated by Django 5.0.7 on 2026-07-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics_engine", "0017_marketplace_recommendation_api_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosticorder",
            name="operational_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Operational workflow metadata (e.g. recommendation_id linkage for business audit).",
            ),
        ),
    ]
