# Generated by Django 5.0.7 on 2026-07-17 07:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0018_diagnosticorder_operational_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diagnosticordertestline',
            index=models.Index(fields=['status', 'updated_at'], name='diag_line_stat_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(fields=['report_number'], name='diag_rpt_number_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(fields=['supersedes', 'deleted_at'], name='diag_rpt_super_del_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(fields=['deleted_at', 'uploaded_at'], name='diag_rpt_del_up_idx'),
        ),
    ]
