# Generated by Django 5.0.7 on 2026-07-17 07:28

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0019_workspace_m11_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diagnostictestreport',
            name='diag_rpt_number_idx',
        ),
        migrations.AddIndex(
            model_name='diagnostictestreport',
            index=models.Index(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('report_number'), name='varchar_pattern_ops'), name='diag_rpt_num_up_pat_idx'),
        ),
    ]
