# Generated by Django 5.0.7 on 2026-07-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics_engine', '0021_remove_unique_active_artifact_per_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticreportartifact',
            name='artifact_type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'Image'), ('CSV', 'CSV'), ('XLSX', 'Excel'), ('DOCX', 'Word'), ('TXT', 'Text'), ('ZIP', 'ZIP'), ('DICOM', 'DICOM')], default='PDF', max_length=20),
        ),
    ]
