# Generated by Django 5.0.7 on 2025-02-27 09:49

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0003_delete_clinicfrontdeskuser'),
        ('doctor', '0017_alter_doctorfeestructure_unique_together_and_more'),
        ('patient_account', '0008_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online')], default='CASH', max_length=10)),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctor.doctor')),
                ('patient_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient_account.patientaccount')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patient_account.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('working_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10), default=list, size=None)),
                ('morning_start', models.TimeField(blank=True, null=True)),
                ('morning_end', models.TimeField(blank=True, null=True)),
                ('evening_start', models.TimeField(blank=True, null=True)),
                ('evening_end', models.TimeField(blank=True, null=True)),
                ('night_start', models.TimeField(blank=True, null=True)),
                ('night_end', models.TimeField(blank=True, null=True)),
                ('break_start', models.TimeField(blank=True, help_text='Lunch/Personal Break Start Time', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Lunch/Personal Break End Time', null=True)),
                ('slot_duration', models.PositiveIntegerField(default=15, help_text='Consultation duration per patient (in minutes)')),
                ('buffer_time', models.PositiveIntegerField(default=5, help_text='Gap between two appointments (in minutes)')),
                ('max_appointments_per_day', models.PositiveIntegerField(default=20, help_text='Daily appointment limit')),
                ('emergency_slots', models.PositiveIntegerField(default=2, help_text='Reserved slots for emergency cases')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic')},
            },
        ),
        migrations.CreateModel(
            name='DoctorFeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_time_consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('follow_up_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('case_paper_duration', models.PositiveIntegerField(help_text='Case paper validity in days')),
                ('case_paper_renewal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emergency_consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('online_consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rescheduling_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic')},
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Start date of the leave')),
                ('end_date', models.DateField(help_text='End date of the leave')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for leave', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_leaves', to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='FollowUpPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('follow_up_duration', models.PositiveIntegerField(help_text='Follow-up validity in days (e.g., 7, 15, 30)')),
                ('follow_up_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_follow_up_visits', models.PositiveIntegerField(default=1, help_text='Maximum follow-ups allowed in duration')),
                ('allow_online_follow_up', models.BooleanField(default=True, help_text='Can follow-up be done online?')),
                ('online_follow_up_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('access_past_appointments', models.BooleanField(default=True, help_text='Can doctor view past visits?')),
                ('access_past_prescriptions', models.BooleanField(default=True, help_text='Can doctor view old prescriptions?')),
                ('access_past_reports', models.BooleanField(default=True, help_text='Can doctor view test reports?')),
                ('access_other_clinic_history', models.BooleanField(default=False, help_text='Can doctor see history from other clinics?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
