# Generated by Django 5.0.7 on 2025-02-27 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinic', '0003_delete_clinicfrontdeskuser'),
        ('doctor', '0017_alter_doctorfeestructure_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorOPDStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=False, help_text='True if doctor is in OPD, False if away')),
                ('check_in_time', models.DateTimeField(blank=True, help_text='When doctor starts OPD', null=True)),
                ('check_out_time', models.DateTimeField(blank=True, help_text='When doctor leaves OPD', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opd_status', to='clinic.clinic')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opd_status', to='doctor.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'clinic')},
            },
        ),
    ]
