# Generated by Django 5.0.7 on 2026-05-02 10:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointmenthistory_options_and_more'),
        ('clinic', '0010_clinic_code'),
        ('doctor', '0031_doctor_public_id'),
        ('patient_account', '0010_patient_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_slot',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_doctor_date_idx',
            old_name='appointment_doctor__4d4b79_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_clinic_date_idx',
            old_name='appointment_clinic__843526_idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='appt_status_idx',
            old_name='appointment_status_8fe9d7_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient_profile'], name='appt_patient_profile_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['scheduled', 'checked_in', 'in_consultation'])), fields=('doctor', 'appointment_date', 'slot_start_time'), name='unique_active_doctor_slot'),
        ),
    ]
