# Generated by Django 5.0.7 on 2025-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_booking_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorleave',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='half_day',
            field=models.BooleanField(default=False, help_text='Is it a half-day leave?'),
        ),
        migrations.AddField(
            model_name='doctorleave',
            name='leave_type',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('vacation', 'Vacation'), ('emergency', 'Emergency'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
