# Generated by Django 5.0.7 on 2026-05-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_list_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_clinic_stat_date_slot_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appt_clinic_doc_date_slot_idx',
        ),
    ]
