"""Stable operational error codes for notification APIs."""

NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND"
PREFERENCE_NOT_FOUND = "PREFERENCE_NOT_FOUND"
VALIDATION_FAILED = "VALIDATION_FAILED"
PERMISSION_DENIED = "PERMISSION_DENIED"
DELIVERY_FAILED = "DELIVERY_FAILED"
CHANNEL_DISABLED = "CHANNEL_DISABLED"
