# Generated by Django 5.0.7 on 2026-05-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_idempotency_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='core_idempo_scope_0fca3a_idx',
            old_name='core_idempo_scope_7a1b0d_idx',
        ),
    ]
