# Generated by Django 5.0.7 on 2026-01-02 07:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('MEETING', 'Meeting'), ('REMINDER', 'Reminder'), ('PERSONAL', 'Personal'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_blocking', models.BooleanField(default=False)),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['doctor', 'start_datetime'], name='calendar_ev_doctor__351fba_idx'), models.Index(fields=['doctor', 'end_datetime'], name='calendar_ev_doctor__f25a80_idx'), models.Index(fields=['category'], name='calendar_ev_categor_4b382b_idx')],
            },
        ),
    ]
