# Generated by Django 5.0.7 on 2025-07-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinicspecialization_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='emergency_contact_number',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='clinic',
            name='emergency_email_address',
            field=models.EmailField(default='NA', max_length=255),
        ),
    ]
