# Generated by Django 5.0.7 on 2025-10-01 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_clinic_emergency_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured in search results'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='kyc_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinic',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='clinic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic.clinic'),
        ),
    ]
