# Generated by Django 5.0.7 on 2025-12-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinicprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clinicschedule',
            unique_together={('clinic', 'day_of_week')},
        ),
        migrations.AddField(
            model_name='clinic',
            name='website_url',
            field=models.URLField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='afternoon_end',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='afternoon_start',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='doctor_checkin_time',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='doctor_checkout_time',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='evening_end',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='evening_start',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='holidays',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='is_doctor_present',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='morning_end',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='morning_start',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='slot_duration',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='special_dates',
        ),
    ]
