# Generated by Django 5.0.7 on 2025-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_clinicschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='emergency_contact_name',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='clinic',
            name='emergency_instructions_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
