# Generated by Django 5.0.7 on 2026-02-14 18:29

from django.db import migrations, models


def add_code_column_if_not_exists(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'clinic_clinic' AND column_name = 'code';
        """)
        if cursor.fetchone() is None:
            cursor.execute("""
                ALTER TABLE clinic_clinic
                ADD COLUMN code VARCHAR(20) NULL UNIQUE;
            """)
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS clinic_clinic_code_idx ON clinic_clinic (code);
            """)


def reverse_add_code(apps, schema_editor):
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE clinic_clinic DROP COLUMN IF EXISTS code;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_clinicholiday'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='clinic',
                    name='code',
                    field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_code_column_if_not_exists, reverse_add_code),
            ],
        ),
    ]
