# Generated by Django 5.0.7 on 2025-02-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_clinic_registration_number_clinicfrontdeskuser'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinics',
            field=models.ManyToManyField(related_name='patients_all', to='clinic.clinic'),
        ),
    ]
