# Generated by Django 5.0.7 on 2024-12-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_mgmt', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitals',
            field=models.ManyToManyField(related_name='patients', to='hospital_mgmt.hospital'),
        ),
    ]
