# Generated by Django 5.0.7 on 2025-07-20 08:00

import diagnostic.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testreport',
            name='file',
            field=models.FileField(max_length=500, upload_to=diagnostic.utils.report_upload_path),
        ),
    ]
