# Generated by Django 5.0.7 on 2025-05-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_consultation_closure_note_and_more'),
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagerecommendation',
            unique_together={('consultation', 'package')},
        ),
    ]
