# Generated by Django 5.0.7 on 2025-07-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_alter_testreport_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcommissionledger',
            name='generated_from',
            field=models.CharField(default='auto', help_text='auto or manual', max_length=20),
        ),
        migrations.AddField(
            model_name='labcommissionledger',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='labcommissionledger',
            index=models.Index(fields=['lab'], name='diagnostic__lab_id_16e735_idx'),
        ),
        migrations.AddIndex(
            model_name='labcommissionledger',
            index=models.Index(fields=['booking'], name='diagnostic__booking_228410_idx'),
        ),
        migrations.AddIndex(
            model_name='labcommissionledger',
            index=models.Index(fields=['test'], name='diagnostic__test_id_2bba2a_idx'),
        ),
        migrations.AddIndex(
            model_name='labcommissionledger',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_bdb58c_idx'),
        ),
    ]
