# Generated by Django 5.0.7 on 2025-07-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_diagnosticlab_labcommissionledger_testbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecommendation',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Doctor-suggested preferred date', null=True),
        ),
    ]
