# Generated by Django 5.0.7 on 2025-07-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_labcommissionledger_generated_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlabmapping',
            name='doctor_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Overrides lab's default doctor commission for this test", max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='testlabmapping',
            name='platform_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Overrides lab's default platform commission for this test", max_digits=5, null=True),
        ),
    ]
