# Generated by Django 5.0.7 on 2025-07-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0003_testrecommendation_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='lab_approved_at',
            field=models.DateTimeField(blank=True, help_text='Time when lab confirmed the booking', null=True),
        ),
        migrations.AddField(
            model_name='testrecommendation',
            name='test_status',
            field=models.CharField(choices=[('RECOMMENDED', 'Recommended'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECOMMENDED', help_text='Track the current state of test', max_length=20),
        ),
    ]
