# Generated by Django 5.0.7 on 2025-10-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_testlabmapping_doctor_commission_percent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labadminuser',
            old_name='mobile_number',
            new_name='secondary_mobile_number',
        ),
        migrations.AddField(
            model_name='labadminuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labadminuser',
            name='kyc_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labadminuser',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labadminuser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labadminuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='labadminuser',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_admin', to='diagnostic.diagnosticlab'),
        ),
        migrations.AlterField(
            model_name='testrecommendation',
            name='test_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='RECOMMENDED', help_text='Track the current state of test', max_length=20),
        ),
    ]
