# Generated by Django 5.0.7 on 2025-07-06 17:47

import diagnostic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_testbooking_lab_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecommendation',
            name='test_pnr',
            field=models.CharField(db_index=True, default=diagnostic.models.generate_test_pnr, max_length=10, unique=True),
        ),
    ]
