# Generated by Django 5.0.7 on 2025-10-09 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_rename_mobile_number_labadminuser_secondary_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name for UI display', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='diagnostic__slug_eac288_idx'), models.Index(fields=['is_active'], name='diagnostic__is_acti_4ef1a6_idx')],
            },
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='service_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories of diagnostic services offered by this lab (e.g., Pathology, Radiology, Imaging)', related_name='labs', to='diagnostic.servicecategory'),
        ),
    ]
