# Generated by Django 5.0.7 on 2025-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0006_servicecategory_diagnosticlab_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='labadminuser',
            name='kyc_document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='labadminuser',
            name='kyc_document_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
