# Generated by Django 5.0.7 on 2025-07-08 18:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0006_labadminuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticLabAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(default='NA', max_length=255)),
                ('address2', models.TextField(default='NA', max_length=255)),
                ('city', models.CharField(default='NA', max_length=100)),
                ('state', models.CharField(default='NA', max_length=100)),
                ('pincode', models.CharField(default='NA', max_length=10)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosticlab',
            name='address',
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='certifications',
            field=models.TextField(blank=True, help_text='e.g., NABL, ISO', null=True),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='home_sample_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='lab_type',
            field=models.CharField(choices=[('collection_center', 'Collection Center'), ('diagnostic_lab', 'Diagnostic Lab'), ('pathology_lab', 'Pathology Lab'), ('radiology_center', 'Radiology Center')], default='diagnostic_lab', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='license_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='pricing_tier',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('premium', 'Premium')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='report_delivery_timings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='sample_pickup_timings',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='test_types_supported',
            field=models.JSONField(blank=True, default=list, help_text="E.g., ['blood', 'urine', 'MRI', 'CT', 'ultrasound']"),
        ),
        migrations.AddField(
            model_name='diagnosticlab',
            name='turnaround_time_hours',
            field=models.IntegerField(default=24, help_text='Default TAT for reports'),
        ),
        migrations.AddIndex(
            model_name='diagnosticlab',
            index=models.Index(fields=['lab_type'], name='diagnostic__lab_typ_6af40a_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticlab',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_588ed3_idx'),
        ),
        migrations.AddField(
            model_name='diagnosticlabaddress',
            name='lab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='diagnostic.diagnosticlab'),
        ),
    ]
