# Generated by Django 5.0.7 on 2025-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0007_diagnosticlabaddress_remove_diagnosticlab_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labadminuser',
            name='mobile_number',
            field=models.CharField(default='NA', max_length=15, unique=True),
        ),
    ]
