# Generated by Django 5.0.7 on 2025-10-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0007_labadminuser_kyc_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticlab',
            name='lab_type',
            field=models.CharField(choices=[('collection_center', 'Collection Center'), ('Diagnostic Lab', 'diagnostic_lab'), ('pathology_lab', 'Pathology Lab'), ('radiology_center', 'Radiology Center')], default='diagnostic_lab', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosticlabaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticlabaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
