# Generated by Django 5.0.7 on 2025-07-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_labadminuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='testcategory',
            index=models.Index(fields=['slug'], name='diagnostic__slug_305521_idx'),
        ),
        migrations.AddIndex(
            model_name='testcategory',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_74abbe_idx'),
        ),
    ]
