# Generated by Django 5.0.7 on 2025-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_alter_diagnosticlab_lab_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labadminuser',
            name='secondary_mobile_number',
            field=models.CharField(default='NA', max_length=15),
        ),
    ]
