# Generated by Django 5.0.7 on 2025-07-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0009_testcategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='medicaltest',
            name='unique_lowercase_test_name',
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='medicaltest',
            index=models.Index(fields=['type'], name='diagnostic__type_599991_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaltest',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_c56b86_idx'),
        ),
        migrations.AddIndex(
            model_name='testpackage',
            index=models.Index(fields=['name'], name='diagnostic__name_adb68d_idx'),
        ),
        migrations.AddIndex(
            model_name='testpackage',
            index=models.Index(fields=['category'], name='diagnostic__categor_5b19cd_idx'),
        ),
        migrations.AddIndex(
            model_name='testpackage',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_3ee997_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicaltest',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('name__isnull', False)), fields=('name',), name='unique_lowercase_test_name'),
        ),
        migrations.AddConstraint(
            model_name='testpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_active_package_name'),
        ),
    ]
