# Generated by Django 5.0.7 on 2025-10-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0009_alter_labadminuser_secondary_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticlab',
            name='lab_type',
            field=models.CharField(choices=[('Collection Center', 'collection_center'), ('Diagnostic Lab', 'diagnostic_lab'), ('Pathology Lab', 'pathology_lab'), ('Radiology Center', 'radiology_center')], default='diagnostic_lab', max_length=100),
        ),
        migrations.AlterField(
            model_name='diagnosticlabaddress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticlabaddress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True),
        ),
    ]
