# Generated by Django 5.0.7 on 2025-07-10 19:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0011_alter_testlabmapping_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageLabMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_available', models.BooleanField(default=True)),
                ('turnaround_time', models.PositiveIntegerField(help_text='In hours')),
                ('home_collection_available', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_mappings', to='diagnostic.diagnosticlab')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_mappings', to='diagnostic.testpackage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lab'], name='diagnostic__lab_id_60b59b_idx'), models.Index(fields=['package'], name='diagnostic__package_b03278_idx'), models.Index(fields=['is_active'], name='diagnostic__is_acti_4aad94_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='packagelabmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('package', 'lab'), name='unique_active_package_lab'),
        ),
    ]
