# Generated by Django 5.0.7 on 2025-07-11 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_advice_unique_custom_advice_per_consultation'),
        ('diagnostic', '0012_packagelabmapping_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='testrecommendation',
            name='unique_consultation_test',
        ),
        migrations.AddField(
            model_name='testrecommendation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='testrecommendation',
            index=models.Index(fields=['consultation'], name='diagnostic__consult_84951f_idx'),
        ),
        migrations.AddIndex(
            model_name='testrecommendation',
            index=models.Index(fields=['test'], name='diagnostic__test_id_6a2e84_idx'),
        ),
        migrations.AddIndex(
            model_name='testrecommendation',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_79ad63_idx'),
        ),
        migrations.AddConstraint(
            model_name='testrecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('test__isnull', False)), fields=('consultation', 'test'), name='unique_consultation_test'),
        ),
    ]
