# Generated by Django 5.0.7 on 2025-07-11 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_advice_unique_custom_advice_per_consultation'),
        ('diagnostic', '0013_alter_testrecommendation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagerecommendation',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_packages', to='diagnostic.testpackage'),
        ),
        migrations.AddIndex(
            model_name='packagerecommendation',
            index=models.Index(fields=['consultation'], name='diagnostic__consult_bd22df_idx'),
        ),
        migrations.AddIndex(
            model_name='packagerecommendation',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_52c1de_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagerecommendation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('consultation', 'package'), name='unique_active_consultation_package'),
        ),
    ]
