# Generated by Django 5.0.7 on 2025-07-12 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_advice_unique_custom_advice_per_consultation'),
        ('diagnostic', '0014_alter_packagerecommendation_package_and_more'),
        ('patient_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='testbooking',
            name='patient',
        ),
        migrations.AddField(
            model_name='testbooking',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_bookings', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='patient_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_bookings', to='patient_account.patientprofile'),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='booked_by',
            field=models.CharField(choices=[('patient', 'Patient'), ('helpdesk', 'Helpdesk')], default='patient', max_length=30),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_bookings', to='diagnostic.diagnosticlab'),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='diagnostic.testrecommendation'),
        ),
        migrations.CreateModel(
            name='BookingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booked_by', models.CharField(choices=[('patient', 'Patient'), ('helpdesk', 'Helpdesk')], default='patient', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Overall group booking status', max_length=20)),
                ('is_home_collection', models.BooleanField(default=False)),
                ('preferred_schedule_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_groups', to='consultations.consultation')),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_groups', to='patient_account.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testbooking',
            name='booking_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_bookings', to='diagnostic.bookinggroup'),
        ),
        migrations.AddIndex(
            model_name='testbooking',
            index=models.Index(fields=['consultation'], name='diagnostic__consult_235727_idx'),
        ),
        migrations.AddIndex(
            model_name='testbooking',
            index=models.Index(fields=['patient_profile'], name='diagnostic__patient_b94018_idx'),
        ),
        migrations.AddIndex(
            model_name='testbooking',
            index=models.Index(fields=['lab'], name='diagnostic__lab_id_af5cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='testbooking',
            index=models.Index(fields=['is_active'], name='diagnostic__is_acti_a408bd_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinggroup',
            index=models.Index(fields=['consultation'], name='diagnostic__consult_302111_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinggroup',
            index=models.Index(fields=['patient_profile'], name='diagnostic__patient_dfe91d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinggroup',
            index=models.Index(fields=['status'], name='diagnostic__status_e3b177_idx'),
        ),
    ]
