# Generated by Django 5.0.7 on 2025-07-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0015_alter_testbooking_options_remove_testbooking_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinggroup',
            name='lab_grouping_type',
            field=models.CharField(choices=[('single_lab', 'Single Lab'), ('multi_lab', 'Multi Lab')], default='single_lab', help_text='Indicates if all tests were booked under one lab or multiple', max_length=20),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='source',
            field=models.CharField(blank=True, help_text='e.g., patient_app, helpdesk_panel', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookinggroup',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='lab_mapping',
            field=models.ForeignKey(blank=True, help_text='Lab mapping used for price/TAT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.testlabmapping'),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='tat_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Snapshot of turnaround time', null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='test_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='testrecommendation',
            name='source',
            field=models.CharField(blank=True, help_text='Indicates how test was added: doctor, patient_upload, external_prescription', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='testreport',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diagnostic.diagnosticlab'),
        ),
    ]
