# Generated by Django 5.0.7 on 2025-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_advice_unique_custom_advice_per_consultation'),
        ('diagnostic', '0016_bookinggroup_lab_grouping_type_bookinggroup_source_and_more'),
        ('patient_account', '0002_patientaccount_is_active_patientprofile_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='testbooking',
            name='unique_booking_per_recommendation',
        ),
        migrations.AddConstraint(
            model_name='testbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('recommendation',), name='unique_booking_per_recommendation'),
        ),
    ]
