# Generated by Django 5.0.7 on 2025-07-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0017_remove_testbooking_unique_booking_per_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='collector_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='collector_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='home_collection_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='home_collection_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='home_collection_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testbooking',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
