# Generated by Django 5.0.7 on 2025-07-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0018_testbooking_collector_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='home_collection_supported',
            field=models.BooleanField(default=True, help_text='Indicates if this test is technically eligible for home sample collection'),
        ),
    ]
