# Generated by Django 5.0.7 on 2025-02-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
