# Generated by Django 5.0.7 on 2025-06-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpdeskclinicuser',
            options={'ordering': ['-created_at']},
        ),
    ]
