# Generated by Django 5.0.7 on 2025-02-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_helpdeskclinicuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='secondary_mobile_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
