# Generated by Django 5.0.7 on 2025-09-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_helpdeskclinicuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='kyc_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
