# Generated by Django 5.0.7 on 2026-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_helpdeskclinicuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskclinicuser',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
