# Generated by Django 5.0.7 on 2026-04-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_helpdeskclinicuser_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpdeskclinicuser',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='helpdeskclinicuser',
            name='kyc_completed',
        ),
        migrations.RemoveField(
            model_name='helpdeskclinicuser',
            name='kyc_verified',
        ),
        migrations.RemoveField(
            model_name='helpdeskclinicuser',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='helpdeskclinicuser',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='helpdeskclinicuser',
            name='status',
        ),
    ]
